---




title: For Debian/Ubuntu

description: Get started on Debian/Ubuntu by installing the rhc command line tools for the RHEL/CentOS operating system.
---

[[top]]
[float]
= OpenShift Online for Debian/Ubuntu
[.lead]
This tutorial is designed to help you get the most out of OpenShift Online on a Debian or Ubuntu machine. In addition to the link:https://openshift.redhat.com/app/console[web interface], OpenShift provides client tools (rhc) to help you create and manage your applications.

OpenShift allows a choice of environments (UI, command line, IDE), but in order to get the most out of your applications, you'll want to at least use the OpenShift client tools (*rhc*).

If you just want to log in and create your first application, you can simply log into the link:https://openshift.redhat.com/app/login?then=%2Fapp%2Fconsole[web console (requires login)]. However, you won't be able to make changes to your application until you've followed the instructions below.

== In this Tutorial
Install the client tools link:#client-tools-dpkg[via Debian package] or link:#client-tools-gem[via Ruby gem] +
link:#rhc-setup[Setting up Your Machine] +
link:#creating-app[Creating an Application] +
link:#making-first-change[Making Your First Change] +
link:#remote-access[Remote Access] +
link:#next-steps[Next Steps] +

[[client-tools-dpkg]]
== Installing the Client Tools via dpkg
The quickest way of installing the tools is using the Debian package. It is available in link:https://packages.debian.org/source/stable/rhc[Debian stable] and link:http://packages.ubuntu.com/vivid/rhc[Ubuntu vivid] or later. If you use a previous version of Ubuntu, refer to the  link:#client-tools-gem[Ruby gem] method.

From terminal, run the following command (requires sudoer or root access):
[source]
----
$ sudo apt-get install rhc
----

NOTE: The `sudo` command only works if the particular user is listed in the _sudoers_ file. As an alternative to sudo access, you can activate a root terminal with the +su+ command and the root password. If you activate a root terminal, omit `sudo` from the commands shown in the examples. Be sure to close the root terminal after the installation completes.

[[client-tools-gem]]
== Installing the Client Tools via Ruby gem
Installing the client tools this way on Ubuntu or Debian requires sudoer or root access and comprises three steps:

*Step 1*: Install *_Ruby_* with *_RubyGems_*

*Step 2*: Install *_Git_*

*Step 3*: Install the client tools

=== Step 1: Install Ruby with RubyGems

From terminal, run the following command to install Ruby:
[source]
----
$ sudo apt-get install ruby-full
----

Run the following command to verify that Ruby has installed correctly:
[source]
----
$ ruby -e 'puts "Welcome to Ruby"'
Welcome to Ruby
----

Rubygems are now part of the ruby package. However, with older Ubuntu repositories, you may need to run the following command to explicitly install RubyGems:
[source]
----
$ sudo apt-get install rubygems
----

=== Step 2: Install Git

Run the following command to install Git version control:
[source]
----
$ sudo apt-get install git-core
----

After installation completes, run the following command to verify that Git has installed correctly:
[source]
----
$ git --version
----

This command returns the Git version number that was installed.

=== Step 3: Install Client Tools

When the required software has been successfully installed, run the following command to install the client tools:
[source]
----
$ sudo gem install rhc
----

link:#top[Back to Top]

include::_fragments/getting-started-setup.adoc[]

include::_fragments/getting-started-tutorial-list.adoc[]

link:#top[Back to Top]
