---




title: For Fedora

description: Get started on Fedora by installing the rhc command line tools for the Fedora operating system.
---


[[top]]
[float]
= OpenShift Online for Fedora
[.lead]
This tutorial is designed to help you get the most out of OpenShift Online on a Fedora machine. In addition to the link:https://openshift.redhat.com/app/console[web interface], OpenShift provides client tools (rhc) to help you create and manage your applications.

OpenShift allows a choice of environments (UI, command line, IDE), but in order to get the most out of your applications, you'll want to at least use the OpenShift client tools (*rhc*).

If you just want to log in and create your first application, you can simply log into the link:https://openshift.redhat.com/app/login?then=%2Fapp%2Fconsole[web console (requires login)]. However, you won't be able to make changes to your application until you've followed the instructions below.

== In this Tutorial
link:#client-tools[Installing the Client Tools] +
link:#rhc-setup[Setting up Your Machine] +
link:#creating-app[Creating an Application] +
link:#making-first-change[Making Your First Change] +
link:#remote-access[Remote Access] +
link:#next-steps[Next Steps] +

[[client-tools]]
== Installing the Client Tools on Fedora
The OpenShift client tools are supported on Fedora 16 or later and require sudoer or root access.

NOTE: The `sudo` command only works if the particular user is listed in the sudoers file. As an alternative to sudo access, you can activate a root terminal with the su command and the root password. If you activate a root terminal, omit `sudo` from the commands shown in the examples. Be sure to close the root terminal when the installation process is complete.

You can install the client tools on Fedora operating systems by installing the gem (recommended), or by installing the RPM with the YUM package manager.

NOTE: The RPM version of the client tools is not updated as frequently as the gem maintained by the OpenShift development team.

=== Install with Gem
From the terminal, install Ruby and RubyGems if they are not already installed:
[source]
----
$ sudo yum install rubygems
----

Install the client tools and all other required dependencies:
[source]
----
$ sudo gem install rhc
----

=== Install with YUM Package Manager
From the terminal, install the client tools and all other required dependencies:
[source]
----
$ sudo yum install rubygem-rhc
----

link:#top[Back to Top]

include::_fragments/getting-started-setup.adoc[]

include::_fragments/getting-started-tutorial-list.adoc[]

link:#top[Back to Top]
