---




title: For Mac/OS X

description: Get started on Mac by installing the rhc command line tools for the OS X operating system.
---

[[top]]
[float]
= OpenShift Online for Mac/OS X
[.lead]
This tutorial is designed to help you get the most out of OpenShift Online on a Mac/OS X machine. In addition to the link:https://openshift.redhat.com/app/console[web interface], OpenShift provides client tools (rhc) to help you create and manage your applications.

OpenShift allows a choice of environments (UI, command line, IDE), but in order to get the most out of your applications, you'll want to at least use the OpenShift client tools (*rhc*).

If you just want to log in and create your first application, you can simply log into the link:https://openshift.redhat.com/app/login?then=%2Fapp%2Fconsole[web console (requires login)]. However, you won't be able to make changes to your application until you've followed the instructions below.

== In this Tutorial
link:#client-tools[Installing the Client Tools] +
link:#rhc-setup[Setting up Your Machine] +
link:#creating-app[Creating an Application] +
link:#making-first-change[Making Your First Change] +
link:#remote-access[Remote Access] +
link:#next-steps[Next Steps] +

[[client-tools]]
== Installing the Client Tools on Mac OS X
The OpenShift Client Tools (rhc) require *Ruby* and *Git*. OS X Lion and Mountain Lion have *Ruby 1.8.7* installed by default. OS X Mavericks and Yosemite use *Ruby 2.0.0* instead.

TIP: On older Mac systems, Ruby is shipped as part of the link:http://developer.apple.com/xcode[Xcode development suite] and can be installed from your installation CD.

If you are familiar with Mac development, you can also use link:http://macruby.org/[MacRuby] or see the
link:http://www.ruby-lang.org/en/downloads/[Ruby installation page] for help installing with homebrew.

To verify that Ruby is correctly installed run:
[source]
----
$ ruby -e 'puts "Welcome to Ruby"'
Welcome to Ruby
----

There are a number of options on Mac OS X for Git, such as link:http://code.google.com/p/git-osx-installer/[Git for OS X] - download and run the latest version of the dmg file on your system.

To verify the Git for OS X installation, run:
[source]
----
$ git --version
git version 1.9.3 (Apple Git-50)
----

With Ruby and Git installed, use the RubyGems library system to install and run the OpenShift gem (rhc). Run:
[source]
----
$ sudo gem install rhc
----

If you encounter any dependency issues, you may need to run:
[source]
----
$ sudo gem update
----

link:#top[Back to Top]

include::_fragments/getting-started-setup.adoc[]

include::_fragments/getting-started-tutorial-list.adoc[]

link:#top[Back to Top]
