---

category:


title: Environment Variables

description: JBoss EAP Environment Variables
---


[float]
= JBoss EAP Environment Variables
The `jbosseap` cartridge provides several environment variables to reference for ease
of use:

[options="header"]
|===
|Variable |Description

|OPENSHIFT_WILDFLY_IP
|The IP address used to bind WildFly

|OPENSHIFT_WILDFLY_HTTP_PORT
|The WildFly listening port

|OPENSHIFT_WILDFLY_CLUSTER_PORT
|TODO

|OPENSHIFT_WILDFLY_USERNAME
|The WildFly admin username

|OPENSHIFT_WILDFLY_PASSWORD
|The WildFly admin password

|OPENSHIFT_WILDFLY_MANAGEMENT_HTTP_PORT
|The WildFly web admin management port

|JAVA_OPTS_EXT
|Appended to JAVA_OPTS prior to invoking the Java VM.
|===

For more information, consult the link:/managing-your-applications/environment-variables.html[Environment Variables] guide.

[[jbosseap-environment-variable-replacement-support]]
*Environment Variable Replacement Support*

The `wildfly` cart provides special environment variable replacement functionality for some of the configuration files. For the following configuration files:

* `.openshift/config/standalone.xml`

Ant-style environment replacements are supported for all `OPENSHIFT_`-prefixed environment variables in the application. For example, the following replacements are valid in `standalone.xml`:

[source, xml]
--
<datasource jndi-name="java:jboss/datasources/MySQLDS" enabled="${mysql.enabled}" use-java-context="true" pool-name="MySQLDS" use-ccm="true">
  <connection-url>jdbc:mysql://${env.OPENSHIFT_MYSQL_DB_HOST}:${env.OPENSHIFT_MYSQL_DB_PORT}/${env.OPENSHIFT_APP_NAME}</connection-url>
  <driver>mysql</driver>
  <security>
    <user-name>${env.OPENSHIFT_MYSQL_DB_USERNAME}</user-name>
    <password>${env.OPENSHIFT_MYSQL_DB_PASSWORD}</password>
  </security>
  <validation>
    <check-valid-connection-sql>SELECT 1</check-valid-connection-sql>
    <background-validation>true</background-validation>
    <background-validation-millis>60000</background-validation-millis>
    <!--<validate-on-match>true</validate-on-match>-->
  </validation>
  <pool>
    <flush-strategy>IdleConnections</flush-strategy>
    <allow-multiple-users/>
  </pool>
</datasource>
--

During server startup, the configuration files in the source repository are processed to replace `OPENSHIFT_*` values, and the resulting processed file is copied to the live WildFly configuration directory.

