---

category:


title: Server Management

description: WildFly OpenShift Server Management
---


[float]
= WildFly Server Management
There are two methods you can use to connect to your WildFly instance for management purposes. You can either use the WildFly CLI tools or you can connect to the WildFly web console.

== JBoss CLI
The `wildfly` cartridge provides an OpenShift compatible wrapper of the JBoss CLI tool on the gear `PATH`, located at `$OPENSHIFT_WILDFLY_DIR/tools/jboss-cli.sh`. After SSH-ing into your application you can use the following command to connect to the WildFly instance with the
CLI tool:

[source]
----
jboss-cli.sh -c --controller=${OPENSHIFT_WILDFLY_IP}:${OPENSHIFT_WILDFLY_MANAGEMENT_HTTP_PORT}
----

Please read link:/managing-your-applications/remote-connection.html[the documentation] on managing remote connections to learn how to SSH to your application. There is also link:https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.3/html/Administration_and_Configuration_Guide/sect-The_Management_CLI.html[documentation] covering how to use the CLI to manage your EAP instance.

== WildFly Web Console
Since the only application TCP ports OpenShift exposes to the outside world are 22, 80, 443, 8000, and 8443, to connect to the JBoss web console you need to use link:http://en.wikipedia.org/wiki/Tunneling_protocol#Secure_Shell_tunneling[SSH port-fowarding] (also called tunneling). If you are unfamiliar with port-forwarding on OpenShift, there is link:https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/User_Guide/sect-Port_Forwarding.html[documentation] to guide you through the process.

If you run the rhc port-forward command, you can access the WildFly management interface on port 9990.
A username and password is created when you install this cartridge.
If you don't write it down, fear not, the following environment variables will contain them.
$OPENSHIFT_WILDFLY_USERNAME
$OPENSHIFT_WILDFLY_PASSWORD

    user$ rhc port-forward wildfly
    Checking available ports ...
    done Forwarding ports ...

To connect to a service running on OpenShift, use the Local address
```
Service Local               OpenShift
------- -------------- ---- -------------------
java    127.0.0.1:8080  =>  127.13.118.129:8080
java    127.0.0.1:9990  =>  127.13.118.129:9990
java    127.0.0.1:9999  =>  127.13.118.129:9999
```
In this example, you would visit 127.0.0.1:9990 to access the WildFly Admin Console from your local computer.
