---
layout: base
category: 37_Core Addons
breadcrumb: Core Addons
parent_url: addons-overview.html
nav_title: phpMyAdmin
nav_priority: 2
meta_desc: phpMyAdmin - OpenShift Resources to help you get started with phpMyAdmin.
---
= phpMyAdmin Overview

[[top]]
[float]
= phpMyAdmin on OpenShift
[.lead]
phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web. phpMyAdmin supports a wide range of operations on MySQL, MariaDB and Drizzle. Frequently used operations (managing databases, tables, columns, relations, indexes, users, permissions, etc) can be performed via the user interface, while you still have the ability to directly execute any SQL statement.


== Installation
phpMyAdmin can be installed using the following command:
[source,console]
--
$rhc cartridge add phpmyadmin -a <appname>
--
NOTE: You must have one of the MySQL cartridges installed for this addon to be installed.

NOTE: You can not install this addon into a scaled application.

[source,console]
--
$rhc cartridge add phpmyadmin -a myapp
Using phpmyadmin-4 (phpMyAdmin 4.0) for 'phpmyadmin'
Adding phpmyadmin-4 to application 'myapp' ... done

phpmyadmin-4 (phpMyAdmin 4.0)
-----------------------------
  Gears:          Located with php-5.4, mysql-5.5
  Connection URL: https://myapp-osexample.rhcloud.com/phpmyadmin/

Please make note of these MySQL credentials again:
  Root User: admin7rQNPN7
  Root Password: e7-39PXbqywu
URL: https://myapp-osexample.rhcloud.com/phpmyadmin/
--
=== Usage
Once you have installed the cartridge, make note of the `Connection URL`, `Root User`, and `Root Password` information that is displayed in your console.
You will need this information to access the phpMyAdmin web application.

You can now paste the `Connection URL` into your web browser and it will ask for your username and password. +
Enter the `Root User` as the username, and the `Root Password` as the password and then click ok.

=== Documentation
For further information about phpMyAdmin, you can visit their link:http://www.phpmyadmin.net/home_page/docs.php[Official Documentation] page.

link:#top[Back to Top]
