---
layout: base
category: 40_Databases
breadcrumb: Databases
parent_url: databases-overview.html
nav_title: Overview
nav_priority: 1
---
= Databases Overview
:source-highlighter: coderay

[[top]]
[[databases]]
[float]
= Databases
OpenShift gives you access to a private database instance with full control - you make the choices, not a hosting provider.

link:#mongodb[MongoDB] + 
A scalable, high-performance, open source NoSQL database by 10gen. You can install the link:#rockmongo[RockMongo] cartridge to administrate your instance from the web.

link:#mysql[MySQL] +
A multi-user, multi-threaded SQL database server. Deploy link:#phpmyadmin[phpMyAdmin] to administrate your dbs from the web.

link:#postgresql[PostgreSQL] +
An advanced Object-Relational database management system.

[[mongodb]]
== MongoDB on OpenShift
The `mongodb` cartridge provides link:http://www.mongodb.org/[MongoDB] on OpenShift. MongoDB is a document-oriented NoSQL database, using JSON-style documents with dynamic schemas. With OpenShift you can easily deploy and run applications backed by MongoDB using your favorite servers and frameworks. Just pick an application framework and get started. If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift.

=== Environment Variables
The `mongodb` cartridge provides several environment variables to reference for ease of use:

[options="header"]
|===
|Variable |Description

|OPENSHIFT_MONGODB_DB_HOST
|The MongoDB IP address

|OPENSHIFT_MONGODB_DB_PORT
|The MongoDB port

|OPENSHIFT_MONGODB_DB_USERNAME
|The MongoDB username

|OPENSHIFT_MONGODB_DB_PASSWORD
|The MongoDB password

|OPENSHIFT_MONGODB_DB_URL
|The MongoDB connection URL (e.g. mongodb://<username>:<password>@<hostname>:<port>/)

|OPENSHIFT_MONGODB_DB_LOG_DIR
|The path to the MongoDB log directory
|===

=== Example Use

Getting a Python app with a MongoDB backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp python-3.3
$ rhc cartridge add mongodb-2.4 -a MyApp
--

These two commands create your "server" and install and configure Python, MongoDB, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

[[rockmongo]]
=== RockMongo
The `rockmongo` cartridge provides http://rockmongo.com/[RockMongo] on OpenShift. In order to add this cartridge to an application, the link:#mongodb[MongoDB] cartridge must already be present. Once installed, RockMongo can be used by navigating to http://_app_-_domain_.rhcloud.com/rockmongo with the MongoDB login credentials.

link:#top[Back to Top]

[[mysql]]
== MySQL on OpenShift

The `mysql` cartridge(s) provides link:http://www.mysql.com/[MySQL] on OpenShift. MySQL is an open-source relational database management system. With OpenShift you can easily deploy and run applications backed by MySQL using your favorite servers and frameworks. Just pick an application framework and get started. If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift.

=== Environment Variables
The `mysql` cartridge provides several environment variables to reference for ease of use:

[options="header"]
|===
|Variable |Description

|OPENSHIFT_MYSQLDB_DB_HOST
|The MySQL IP address

|OPENSHIFT_MYSQLDB_DB_PORT
|The MySQL port

|OPENSHIFT_MYSQLDB_DB_LOG_DIR
|The path to the MySQL log directory

|OPENSHIFT_MYSQL_VERSION
|The version of the MySQL server

|OPENSHIFT_MYSQL_TIMEZONE
|The MySQL server timezone

|OPENSHIFT_MYSQL_LOWER_CASE_TABLE_NAMES
|Sets how the table names are stored and compared

|OPENSHIFT_MYSQL_DEFAULT_STORAGE_ENGINE
|The default storage engine (table type)

|OPENSHIFT_MYSQL_MAX_CONNECTIONS
|The maximum permitted number of simultaneous client connections

|OPENSHIFT_MYSQL_FT_MIN_WORD_LEN
|The minimum length of the word to be included in a FULLTEXT index.

|OPENSHIFT_MYSQL_FT_MAX_WORD_LEN
|The maximum length of the word to be included in a FULLTEXT index.

|OPENSHIFT_MYSQL_AIO
|Controls the 'innodb_use_native_aio' setting value in case the native AIO is broken. See http://help.directadmin.com/item.php?id=529
|===

=== Example Use

Getting a PHP app with a MySQL backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp php-5.4
$ rhc cartridge add mysql-5.5 -a MyApp
--

These two commands create your "server" and install and configure PHP, MySQL, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

[[phpmyadmin]]
=== phpMyAdmin
The `phpmyadmin` cartridge provides http://www.phpmyadmin.net[phpMyAdmin] on OpenShift. In order to add this cartridge to an application, the link:#mysql[MySQL] cartridge must already be present. Once installed, phpMyAdmin can be used by navigating to http://_app_-_domain_.rhcloud.com/phpmyadmin with the MySQL login credentials.

link:#top[Back to Top]

[[postgresql]]
== PostgreSQL on OpenShift

The `postgresql` cartridge(s) provides link:http://www.postgresql.com/[PostgreSQL] on OpenShift. PostgreSQL is an open-source object-relational database system. With OpenShift you can easily deploy and run applications backed by PostgreSQL using your favorite servers and frameworks. Just pick an application framework and get started. If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift.

=== Environment Variables
The `postgresql` cartridge provides several environment variables to reference for ease of use:

[options="header"]
|===
|Variable |Description

|OPENSHIFT_POSTGRESQL_DB_HOST
|Numeric host address

|OPENSHIFT_POSTGRESQL_DB_PORT
|Port

|OPENSHIFT_POSTGRESQL_DB_USERNAME
|DB Username

|OPENSHIFT_POSTGRESQL_DB_PASSWORD
|DB Password

|OPENSHIFT_POSTGRESQL_DB_LOG_DIR
|Directory for log files

|OPENSHIFT_POSTGRESQL_DB_PID
|PID of current Postgres server

|OPENSHIFT_POSTGRESQL_DB_SOCKET_DIR
|Postgres socket location

|OPENSHIFT_POSTGRESQL_DB_URL
|Full server URL of the form "postgresql://user:password@host:port"

|OPENSHIFT_POSTGRESQL_VERSION
|PostgreSQL version in the form `X.Y`
|===

You can fine-tune the PostgreSQL server performance by using the rhc tool and changing the default values for these variables:

[options="header"]
|===
|Variable |Description

|OPENSHIFT_POSTGRESQL_SHARED_BUFFERS
|The shared_buffers configuration parameter determines how much memory is dedicated to PostgreSQL to use for caching data.

|OPENSHIFT_POSTGRESQL_MAX_CONNECTIONS
|max_connections sets exactly that: the maximum number of client connections allowed.
|===

For more details, please refer to the PostgreSQL link:https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server[wiki page].

=== Example Use

Getting a Python app with a PostgreSQL backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp python-3.3
$ rhc cartridge add postgresql-9.2 -a MyApp
--

These two commands create your "server" and install and configure Python, PostgreSQL, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

link:#top[Back to Top]