---
layout: base
category: 30_Databases
breadcrumb: Databases
parent_url: databases-overview.html
nav_title: Overview
nav_priority: 1
meta_desc: An overview of database guides on OpenShift.
---
= Management Overview

[[top]]
[float]
= Overview of Database Guides
[.lead]
OpenShift Online offers a numbers of database options to help you get your applications up and running quickly.




== Database Services
link:#mysql[MySQL] +
link:#mongodb[MongoDB] +
link:#postgresql[PostgreSQL] +
link:#sqlite[SQLite] +
link:#amazonrds[Amazon RDS] +

[[mysql]]
=== MySQL
A multi-user, multi-threaded SQL database server. The world's second most widely used relational database management system (RDBMS) and most widely used open-source RDBMS.  Deploy *phpMyAdmin* to administrate your dbs from the web. +
link:databases-mysql.html[-> Learn More]

[[mongodb]]
=== MongoDB
MongoDB is the only database that harnesses the innovations of NoSQL (flexibility, scalability, performance) and builds on the foundation of relational databases (expressive query language, secondary indexes, strong consistency).  You can install the *RockMongo* cartridge to administrate your instance from the web. +
link:databases-mongodb.html[-> Learn More]

[[postgresql]]
=== PostgreSQL
PostgreSQL is a powerful, open source object-relational database system. It has more than 15 years of active development and a proven architecture that has earned it a strong reputation for reliability, data integrity, and correctness. It runs on all major operating systems, including Linux, UNIX (AIX, BSD, HP-UX, SGI IRIX, Mac OS X, Solaris, Tru64), and Windows. It is fully ACID compliant, has full support for foreign keys, joins, views, triggers, and stored procedures (in multiple languages). +
link:databases-postgresql.html[-> Learn More]

[[sqlite]]
=== SQLite
SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine. SQLite is the most widely deployed SQL database engine in the world. The source code for SQLite is in the public domain. +
link:databases-sqlite.html[-> Learn More]

[[amazonrds]]
=== Amazon RDS
Amazon Relational Database Service (Amazon RDS) is a web service that makes it easy to set up, operate, and scale a relational database in the cloud. It provides cost-efficient and resizable capacity while managing time-consuming database management tasks, freeing you up to focus on your applications and business. +
link:databases-amazon-rds.html[-> Learn More]

