---
layout: base
category: 04_Databases and Technologies
breadcrumb: Databases and Technologiess
parent_url:
nav_title: MongoDB
nav_priority: 2
meta_desc: MongoDB Developers - OpenShift Resources to get your Mongo applications hosted in the cloud.
---
= MongoDB Overview

[[top]]
[float]
= MongoDB on OpenShift
[.lead]
The `mongodb` cartridge provides link:http://www.mongodb.org/[MongoDB] on OpenShift. MongoDB is a document-oriented NoSQL database, using JSON-style documents with dynamic schemas. With OpenShift you can easily deploy and run applications backed by MongoDB using your favorite servers and frameworks. OpenShift Online currently supports `MongoDB 2.4`.

== The MongoDB Cartridge

=== Environment Variables
The `mongodb` cartridge provides several environment variables to reference for ease of use:

[options="header"]
|===
|Variable |Description

|OPENSHIFT_MONGODB_DB_HOST
|The MongoDB IP address

|OPENSHIFT_MONGODB_DB_PORT
|The MongoDB port

|OPENSHIFT_MONGODB_DB_USERNAME
|The MongoDB username

|OPENSHIFT_MONGODB_DB_PASSWORD
|The MongoDB password

|OPENSHIFT_MONGODB_DB_URL
|The MongoDB connection URL (e.g. mongodb://<username>:<password>@<hostname>:<port>/)

|OPENSHIFT_MONGODB_DB_LOG_DIR
|The path to the MongoDB log directory
|===

=== Example Use

Getting a Python app with a MongoDB backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp python-3.3
$ rhc cartridge add mongodb-2.4 -a MyApp
--

These two commands create your "server" and install and configure Python, MongoDB, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

[[rockmongo]]
=== RockMongo
The `rockmongo` cartridge provides http://rockmongo.com/[RockMongo] on OpenShift. In order to add this cartridge to an application, the link:#mongodb[MongoDB] cartridge must already be present. Once installed, RockMongo can be used by navigating to http://_app_-_domain_.rhcloud.com/rockmongo with the MongoDB login credentials.
