---
layout: base
category: 03_Languages
breadcrumb: Languages
parent_url: diy-overview.html
nav_title: DIY/Custom
nav_priority: 200
meta_desc: Do-it-yourself Developers - OpenShift Resources to get your custom applications hosted in the cloud.
---
= DIY Overview

[[top]]
[float]
= DIY Application Hosting
[.lead]
The `diy` cartridge provides a minimal, free-form scaffolding which leaves all details of the cartridge to the application developer.

=== Get started
. Add the framework of choice to your repo.
. Modify `.openshift/action_hooks/start` to start your application. The application is required to bind to `$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT`.
. Modify `.openshift/action_hooks/stop` to stop your application.
. Commit and push your changes.

=== Repo layout
[source]
--
static/           Externally exposed static content goes here
.openshift/
    action_hooks/ See the Action Hooks documentation <1>
        start     Custom action hook used to start your application
        stop      Custom action hook to stop your application
--
<1> link:http://openshift.github.io/documentation/oo_user_guide.html#action-hooks[Action Hooks] documentation

NOTE: Please leave the `static` directory in place (alter but do not delete) but feel free to create additional directories if needed.

=== Environment Variables
The `diy` cartridge provides the following environment variables to reference for ease of use:

OPENSHIFT_DIY_IP:: The IP address assigned to the application
OPENSHIFT_DIY_PORT:: The port assigned to the the application

For more information about environment variables, consult the link:http://openshift.github.io/documentation/oo_user_guide.html#environment-variables[Users Guide]
