---
layout: base
category: 14_FAQs
breadcrumb: FAQs
parent_url: managing-overview.html
nav_title: Marketplace FAQs
nav_priority: 10
meta_desc: This page provides answers to questions about the OpenShift Marketplace.
---
= Marketplace FAQs

[[top]]
[float]
= Common Questions
[.lead]
Find answers to questions about the OpenShift Marketplace.

== In This Guide
link:#_what_is_happening_with_the_openshift_online_marketplace[What is happening with the OpenShift Online Marketplace?] +
link:#_when_is_this_taking_place[When is this taking place?] +
link:#_what_happens_to_any_existing_add-ons_that_my_applications_are_using_with_the_marketplace[What happens to any existing add-ons that my applications are using with the marketplace?] +
link:#_why_is_the_marketplace_being_retired_before_the_new_openshift_online_environment_is_available[Why is the marketplace being retired before the new OpenShift Online environment is available?] +
link:#_when_can_we_expect_the_new_marketplace_to_be_available[When can we expect the new marketplace to be available?] +
link:#_without_the_marketplace,_and_until_the_new_marketplace_is_available,_where_can_i_go_to_find_out_what_partner_technologies_are_available_to_work_with_openshift_online[Without the marketplace, and until the new marketplace is available, where can I go to find out what partner technologies are available to work with OpenShift Online?] +
link:#_where_can_partners_that_want_to_work_with_next_generation_of_openshift_online_and_the_marketplace_go_in_the_interim[Where can partners that want to work with next generation of OpenShift Online and the Marketplace go in the interim?] +
link:#_migration_guide[Migration Guide] +

[WARNING]
====
*OpenShift Marketplace will be discontinued after April 4th, 2016* +
All OpenShift Marketplace bindings will cease to work after April 4th, 2016. Please read and follow this link:#_migration_guide[*Migration Guide*] before April 4th, 2016 to ensure continuity of service.
====

=== What is happening with the OpenShift Online Marketplace?

As part of our efforts to move OpenShift Online to be based on our next-generation platform built with Docker and Kubernetes, the OpenShift team is designing and implementing a next-generation marketplace for our customers and partners. As such, the existing marketplace will be sunset in order for us to continue our migration -- discontinuing the marketplace is just one step in a longer journey.

link:#top[Back to Top]

=== When is this taking place?

Currently, the marketplace is scheduled to be retired at 12:01AM on April 5, 2016.

link:#top[Back to Top]

=== What happens to any existing add-ons that my applications are using with the marketplace?

If you are utilizing any partner technologies from the marketplace, then you will need to set up an account directly with the partner technology going forward. After this, you will need to bind your OpenShift application by manually creating environment variables as currently done today with the automatic binding. General instructions for this can be found in the OpenShift Developer Portal.

link:#top[Back to Top]

=== Why is the marketplace being retired before the new OpenShift Online environment is available?

The usage paradigm for a marketplace in the new platform (based on Docker and Kubernetes) will be drastically different from the existing OpenShift Online environment. As such, the resources needed to maintain the current marketplace while simultaneously moving our customers and partners to the new environment is not a trivial endeavour, so the decision was made to help move customers to a more direct relationship with any partner technologies being consumed until the new platform is in place. Once the next-generation marketplace is available, customers will have a  choice of continuing a direct relationship with a partner or via the new integration model.

link:#top[Back to Top]

=== When can we expect the new marketplace to be available?

We currently do not have an estimated timeframe for when the new marketplace alternative will be available. However, it will be after the next-generation OpenShift Online is in place.

link:#top[Back to Top]

=== Without the marketplace, and until the new marketplace is available, where can I go to find out what partner technologies are available to work with OpenShift Online?

The OpenShift Hub is the go-to place to understand and learn about all of the community and commercial technologies that can be integrated with OpenShift Online.

link:#top[Back to Top]

=== Where can partners that want to work with next generation of OpenShift Online and the Marketplace go in the interim?

Please contact us at openshift-partners@redhat.com and we can look into your request.

link:#top[Back to Top]

=== Migration Guide

*To avoid an interruption in your services, please perform the following actions as soon as possible:*

. Sign up for a subscription directly with the external service provider by visiting the provider's website. A full list of providers can be found link:https://hub.openshift.com/addons/types/external[here].
. Migrate any data from your OpenShift Marketplace linked account to your new account.
. Log in to your account at link:https://marketplace.openshift.com[marketplace.openshift.com], disconnect your services from your OpenShift applications, and cancel your subscriptions.
. Follow our guide for integrating external services with your applications - you'll need to set environment variables using the credentials from your new subscription created in Step 1 above.

Detailed instructions for each of our OpenShift Marketplace services can be found in the link:/en/external-services-overview.html[External Services] section of the Developer Portal.

link:#top[Back to Top]