---
layout: base
category: 10_Getting Started
breadcrumb: Getting Started
parent_url: getting-started-overview.html
nav_title: For RHEL/CentOS
nav_priority: 10.3
meta_desc: Get started on RHEL/CentOS by installing the rhc command line tools for the RHEL/CentOS operating system.
---
= OpenShift Online for RHEL/CentOS

[[top]]
[float]
= OpenShift Online for RHEL/CentOS
[.lead]
This tutorial is designed to help you get the most out of OpenShift Online on a RHEL or CentOS machine. In addition to the link:https://openshift.redhat.com/app/console[web interface], OpenShift provides client tools (rhc) to help you create and manage your applications.

OpenShift allows a choice of environments (UI, command line, IDE), but in order to get the most out of your applications, you'll want to at least use the OpenShift client tools (*rhc*).

If you just want to log in and create your first application, you can simply log into the link:https://openshift.redhat.com/app/login?then=%2Fapp%2Fconsole[web console (requires login)]. However, you won't be able to make changes to your application until you've followed the instructions below.

== In this Tutorial
link:#client-tools[Installing the Client Tools] +
link:#rhc-setup[Setting up Your Machine] +
link:#creating-app[Creating an Application] +
link:#making-first-change[Making Your First Change] +
link:#remote-access[Remote Access] +
link:#next-steps[Next Steps] +

[[client-tools]]
== Installing the Client Tools on RHEL or CentOS
You must have the following to successfully install the client tools:
* Red Hat Enterprise Linux 6 or later
* Sudoer or root access
* Ruby and RubyGems installed (including rubygem-json and rubygem-parseconfig)

NOTE: The `sudo` command only works if the particular user is listed in the sudoers file. As an alternative to sudo access, you can activate a root terminal with the su command and the root password. If you activate a root terminal, omit `sudo` from the commands shown in the examples. Be sure to close the root terminal when the installation process is complete.

=== Install RubyGems
If the RubyGems package is not already installed, you must enable the Red Hat Enterprise Linux optional repository channel. The RubyGems package dependencies are then automatically resolved when the client tools are installed.

If you are using the Certificate-Based Red Hat Network (RHN) tooling, use the following command to enable the optional channel:

[source]
----
$ sudo yum-config-manager --enable [architecture][operating_system]-optional-6
----

If you are using the classic RHN subscription, use the following command to enable the optional channel:
[source]
----
$ sudo rhn-channel --add --channel=[architecture]-[operating_system]-optional-6
----

* _architecture_: Your system architecture. Enter either _i386_ or _x86_64_
* _operating system_:  Type of operating system installed. Enter either _workstation_ or _server_.

For example, if you have Red Hat Enterprise Linux Workstation 6 or later installed on a 64-bit x86 computer, and you are using the classic Red Hat Network subscription, run the following command to enable the optional repository:

[source]
----
$ sudo rhn-channel --add --channel=rhel-x86_64-workstation-optional-6
----

=== Install Client Tools
Ensure that the RubyGems software package is installed on your system. Otherwise, the optional repository channel must be enabled on systems that are registered on RHN.

Run the following command to install the client tools:
[source]
----
$ sudo gem install rhc
----

Update rhc to the latest version:
[source]
----
$ sudo gem update rhc
----

link:#top[Back to Top]

include::_fragments/getting-started-setup.adoc[]

include::_fragments/getting-started-tutorial-list.adoc[]

link:#top[Back to Top]
