---
layout: jbosseap
category:
breadcrumb: Languages and Technologies
parent_url: languages-overview.html
nav_title: Server Management
nav_priority: 30
meta_desc: JBoss EAP OpenShift Server Management
---
= JBoss EAP Server Management

[float]
= JBoss EAP Server Management

There are two methods you can use to connect to your JBoss EAP instance for management purposes. You can either use the JBoss EAP CLI tools or you can connect to the JBoss EAP web console.

== JBoss CLI
The `jbosseap` cartridge provides an OpenShift compatible wrapper of the JBoss CLI tool on the gear `PATH`, located at
`$OPENSHIFT_JBOSSEAP_DIR/tools/jboss-cli.sh`. After SSH'ing into your application you can use the following command to connect to the JBoss instance with the
CLI tool:

[source]
--
jboss-cli.sh -c --controller=${OPENSHIFT_JBOSSEAP_IP}:${OPENSHIFT_JBOSSEAP_MANAGEMENT_NATIVE_PORT}
--

Please read link:managing-remote-connection.html[the documentation] on managing remote connections to learn how to SSH to your application. There is also link:https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.3/html/Administration_and_Configuration_Guide/sect-The_Management_CLI.html[documentation] covering how to use the CLI to manage your EAP instance.

== JBoss EAP Web Console

Since the only application TCP ports OpenShift exposes to the outside world are 22, 80, 443, 8000, and 8443, to connect to the JBoss web console you need to use link:http://en.wikipedia.org/wiki/Tunneling_protocol#Secure_Shell_tunneling[SSH port-fowarding] (also called tunneling). If you are unfamiliar with port-forwarding on OpenShift, there is link:https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/User_Guide/sect-Port_Forwarding.html[documentation] to guide you through the process.

Once you have the tunneling set up you should see the following output on your console screen

[source, console]
--

$ rhc port-forward myeap_app
Checking available ports ... done
Forwarding ports ...

To connect to a service running on OpenShift, use the Local address

Service Local               OpenShift
------- -------------- ---- ----------------
java    127.0.0.1:3528  =>  127.9.142.1:3528
java    127.0.0.1:4447  =>  127.9.142.1:4447
java    127.0.0.1:5445  =>  127.9.142.1:5445
java    127.0.0.1:5455  =>  127.9.142.1:5455
java    127.0.0.1:8082  =>  127.9.142.1:8080
java    127.0.0.1:8787  =>  127.9.142.1:8787
java    127.0.0.1:9990  =>  127.9.142.1:9990 <1>
java    127.0.0.1:9999  =>  127.9.142.1:9999

Press CTRL-C to terminate port forwarding

--
<1> port 9990 is the standard port for the JBoss EAP management console

Now to bring up the console all you have to do is go to http://127.0.0.1:9990 in your local browser and use the management console. You will be logged in as an administrator and can do all the link:https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.3/html/Administration_and_Configuration_Guide/sect-The_Management_Console.html[normal tasks and monitoring] available in the EAP console.  

