---
layout: jbosseap
category:
breadcrumb: Languages and Technologies
parent_url: languages-overview.html
nav_title: Deployment Options
nav_priority: 10
meta_desc: Get started with JBoss EAP 6 on OpenShift
---

= Getting Started

[[top]]
[float]
= Getting Started with JBoss EAP 6 on OpenShift

It's easy to get up and running with JBoss EAP (EAP) on OpenShift and the experience will be very similar to the experience of running it on any Linux system. OpenShift supports both source and WAR file deploys and modification of `standalone.xml`. One important caveat - applications will not have write permissions to the `{EAP Home}/standalone/deployments` directory, so you will have to write content to another directory. Finally, given the usual memory requirements of Enterprise Java applications, it is recommended to use a Large or Medium gear size.

link:#step1[Step 1: Create a JBoss EAP Application] +
link:#step2[Step 2: Make the First Change] +
link:#step3[Step 3: Deploying a WAR File] +
// link:#other[Other Tips] +
// link:#next[Next Steps]

[[step1]]
== Step 1: Create a JBoss EAP (EAP) Application

This tutorial walks through the creation of an application titled *myeapapp* under the domain *mydomain*. Before going through the rest of the tutorial, make sure to have link:https://www.openshift.com/app/account[created an OpenShift account] and link:getting-started-client-tools.html[installed the RHC command line tools].

Once that is completed, open a terminal on a local machine and change into a directory where the source code will be located.  Then at the command prompt enter the follwing command to create a EAP application:

[source, console]
--
$ rhc app-create myeapapp jbosseap
--


The output will look something like this:

[source, console]
--
Using jbosseap-6 (JBoss Enterprise Application Platform 6) for 'jbosseap'

Application Options
-------------------
Domain:     spdemo
Cartridges: jbosseap-6 (addtl. costs may apply)
Gear Size:  default
Scaling:    no

Creating application 'myeapapp' ... done


Waiting for your DNS name to be available ... done

Cloning into 'myeapapp'...
Warning: Permanently added 'myeapapp-mydomain.rhcloud.com' (RSA) to the list of known hosts.

Your application 'myeapapp' is now available.

  URL:        http://myeapapp-mydomain.rhcloud.com/ <1>
  SSH to:     541a13a04382ec00000002f3@myeapapp-mydomain.rhcloud.com
  Git remote: ssh://541a13a04382ec00000002f3@myeapapp-mydomain.rhcloud.com/~/git/myeapapp.git/ <2>
  Cloned to:  /home/me/git_demo/myeapapp

Run 'rhc show-app myeapapp' for more details about your app.

--
<1> Public URL of application
<2> Location of local Git repository

The application will now be running and accessible at the *URL (1)* listed in the output. A local git repository for your application was also created in the directory listed under *Cloned to (2)*.

link:#top[Back to Top]

[[step2]]
== Step 2: Make the First Change
A developer on OpenShift can make code changes on a local machine, check those changes in locally, and then `push` those changes to OpenShift. One of the primary advantages of Git is that it does not require a continuous online presence in order to run. A developer can easily check in (in Git terminology, `commit`) and revert changes locally before deciding to upload those changes to OpenShift.

=== Using the Git Repository

To make the first change, edit `index.html` in the `myeapapp/src/main/webapp` directory of the local Git repository. Go to the file in the terminal and edit with a command line editor like *VIM* or *EMacs*. Alternatively, edit the file using any text editor or IDE. Strip out everything between the two `<body>` tags and change the content to look like this:

[source, html]
--
<body>
	<h1>Hello world!</h1>
</body>
--

Now that you have made this incredibly complicated code change, the code must be deployed to the server. Accomplish this task using *Git*.


. To add the change to the Git repository's index and stage it for the next commit, use the command `git add`:
+
[source, console]
--
$ git add --all .
--
+
. Next `commit` the staged changes to the Git repository, with a log message to explain the changes:
+
[source, console]
--
$ git commit -m "Your commit message"
--
+
. Finally, `push` these changes to the remote OpenShift application.
+
[source, console]
--
$ git push
--

The output of the push command will first show the git push and then the build process and deployment for the OpenShift application. When the build is finished, go back to the application's URL (_myeapapp-mydomain.rhcloud.com_) and see a page which just says "Hello World" in nice big font.

This is the basic process to follow when developing an application: `git add`, `git commit`, and finally `git push`.

If you are curious about Git or would like to learn more, the link:http://git-scm.com/book[Pro Git book] is a great resource.

link:#top[Back to Top]

[[step3]]
== Step 3: Deploying WAR files

OpenShift also supports WAR files deployment. There are several processes which are each very simple. There is a https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges[Knowledge Base article] that covers deploying WAR files with both Git and SFTP/SCP.

link:#top[Back to Top]



