---
layout: base
category: 03_Languages and Technologies
breadcrumb: Languages and Technologies
parent_url: languages-overview.html
nav_title: Cartridge Overview
nav_priority: 0.5
meta_desc: A list of fully-supported languages on OpenShift Online
---
= OpenShift Cartridge Overview

[float]
= OpenShift Online Cartridge Overview
[.lead]
OpenShift provides a wide range of languages and services, deployed in applications through a cartridge. Cartridges can be web frameworks, databases, monitoring services, or connectors to external backends.

For a full list of currently supported cartridge technologies, please visit the link:https://www.openshift.com/products/technologies[Technologies] page.

== OpenShift Runtime Environments
OpenShift Online supports a variety of programming languages and runtimes.

=== Java
OpenShift allows extreme flexibility in working with your preferred runtime and framework, with support for *JBossAS*, *Wildfly*, *JBoss EAP*, *Apache Tomcat*, and *Spring*. You can also extend your applications with a number of JBoss xPaaS services, such as *Fuse*, *Data Virtualization*, *BPM Suite*, or *Aerogear Push*. +
link:java-overview.html[-> Learn More]

=== PHP
OpenShift provides many options for PHP developers. Along with support for many popular PHP frameworks such as *CodeIgniter*, *CakePHP* and *Yii*, OpenShift Online has a vast selection of PHP quickstarts that can get you up and running with applications like *Wordpress*, *Drupal* and *Magento* in just a few minutes. +
link:php-overview.html[-> Learn More]

=== Node.js
A platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices. +
link:node-js-overview.html[-> Learn More]

=== Python
Python is a general-purpose, high-level programming language whose design philosophy emphasizes code readability. With OpenShift you can easily deploy and run Python applications using your favorite frameworks and databases. +
link:python-overview.html[-> Learn More]

=== Ruby
With OpenShift, you can create robust Ruby applications without the need for application changes or proprietary APIs. You can also use one of our quickstarts for hassle-free deployment that is extensible and secure. +
link:ruby-overview.html[-> Learn More]

=== Perl
Want a Dancer application backed by MySQL? Or maybe you're looking for Mojolicious and MongoDB? If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift. +
link:perl-overview.html[-> Learn More]

=== Vert.x
A lightweight, high performance application platform for the JVM that's designed for modern mobile, web, and enterprise applications. Vert.x allows you to write reactive applications taking advantage of the built in distributed event bus all using simple and powerful asynchronous API's which can be written in various languages like Java, JavaScript, Ruby, Groovy, and Python. +
link:vertx-overview.html[-> Learn More]

=== DIY
The diy cartridge provides a minimal, free-form scaffolding which leaves all details of the cartridge to the application developer. +
link:diy-overview.html[-> Learn More]

=== Custom
Using a downloadable cartridge, you can easily bring your own frameworks and technologies to OpenShift, reducing the need to set up a DIY cart. link:get-involved-extend-openshift.html[Read our guides] on creating and using your own cartridges. +
link:get-involved-extend-openshift.html[-> Learn More]

== Database Services
Extend your application with a number of powerful database and addon cartridges.

=== MySQL
A multi-user, multi-threaded SQL database server. Deploy *phpMyAdmin* to administrate your dbs from the web. +
link:databases-mysql.html[-> Learn More]

=== MongoDB
A scalable, high-performance, open source NoSQL database by 10gen. You can install the *RockMongo* cartridge to administrate your instance from the web. +
link:databases-mongodb.html[-> Learn More]

=== PostgreSQL
An advanced Object-Relational database management system. +
link:databases-postgresql.html[-> Learn More]

== Continuous Integration and Tools

=== Jenkins
Jenkins is a continuous integration (CI) build server that is deeply integrated into OpenShift. When you add Jenkins as an application you will enable your other applications to run complex builds whenever you push code. The Jenkins client connects to your Jenkins application and enables builds and testing of your application. Requires one Jenkins application to be created first. +
link:managing-continuous-integration.html[-> Learn More]

===  Cron
Allows you to run command line programs at scheduled times. Use this for background jobs and periodic processing. +
link:managing-background-jobs.html[-> Learn More]
