---
layout: base
category: 17_Managing Your Applications
breadcrumb: Managing Your Applications
parent_url: managing-overview.html
nav_title: Markers
nav_priority: 82
meta_desc: Control your app using markers.
---
= Markers

[[top]]
[float]
= Markers
[.lead]
Marker files can be used to customize various aspects of the cartridge's build and deployment process.


[[using-markers]]
== Using markers
Enabling a marker is as simple as creating an empty file of a given name in the `.openshift/markers/` directory and link:managing-modifying-applications.html[pushing] it to your repository, in order to trigger the required functionality.

TIP: For example, creating the `.openshift/markers/hot_deploy` in an PHP app will prevent the Apache process from being restarted during the link:managing-deployments.html[deployment].

Creating an empty file in the current directory is typically done using `touch marker_file` on Linux and Mac OS systems or by `copy NUL > marker_file` when on Windows.

[[common-markers]]
== Common markers
Although markers are generally cartridge-specific, you can expect these to work with most of the cartridges:

[cols="1,3",options="header"]
|===
|Marker |Effect

|disable_auto_scaling
|Will prevent scalable applications from scaling up or down according to application load.

|force_clean_build
|Will remove all previous dependencies and start installing required dependencies from scratch

|hot_deploy
|Will prevent shutdown and startup of the application during builds.
|===

[[cartridge-specific-markers]]
== Cartridge-specific markers
Below you can find links to markers available in various cartridges:

link:jbossas-markers.html[JBoss AS markers] +
link:jbosseap-markers.html[JBoss EAP markers] +
link:node-js-project-structure.html#markers[Node.js markers] +
link:perl-overview.html#_markers[Perl markers] +
link:php-markers.html[PHP markers] +
link:python-markers.html[Python markers] +
link:ruby-markers.html[Ruby markers] +
link:tomcat-markers.html[Tomcat (JBoss EWS) markers] +
link:wildfly-markers.html[WildFly markers] +

link:#top[Back to Top]
