---
layout: base
category: 05_Managing Your Applications
breadcrumb: Managing Your Applications
parent_url:
nav_title: Connecting Client Tools
nav_priority: 10
---
= Connecting Client Tools

[float]
= Client Tools
The OpenShift Client tools, known as rhc, are built and packaged using the Ruby programming language. OpenShift integrates with the Git version control system to provide powerful, decentralized version control for your application source code.

OpenShift rhc can be run on any operating system with Ruby 1.8.7 or higher assuming you have the requisite user permissions to install programs. Instructions for specific operating systems are provided below. It is assumed that you are running the commands from a command line window, such as Command Prompt, or Terminal.

If you are using link:#rvm[Ruby
Version Manager (rvm) see the instructions below].

include::_fragments/overview-client-tools-windows.adoc[]
include::_fragments/overview-client-tools-osx.adoc[]
include::_fragments/overview-client-tools-fedora.adoc[]
include::_fragments/overview-client-tools-rhel6.adoc[]
include::_fragments/overview-client-tools-ubuntu.adoc[]
include::_fragments/overview-client-tools-rvm.adoc[]

[[staying-current]]
== Staying Current

Once you've installed the rhc gem, it's very easy to update. Ruby
includes a built in mechanism for updating libraries. Just run:
[source]
----------------
$ gem update rhc
----------------

or
[source]
---------------------
$ sudo gem update rhc
---------------------

and you'll get the latest version of the tools. Be sure to check your
specific Operating System instructions above if you have any problems.

[[other-sources-of-reference-material]]
== Other sources of reference material

For more help see our link:/developers/get-help[Get Help] page.

Check out the https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/Client_Tools_Installation_Guide/index.html[detailed installation guide for
RHC client tools].
