---
layout: nodejs
category:
breadcrumb: Languages
parent_url: languages-overview.html
nav_title: Getting Started
nav_priority: 24
meta_desc: Getting Started with Node.js hosting on OpenShift
---
= Node.js Getting Started

[float]
= Getting Started with Nodejs
In addition to the usual `git` and the `rhc` command-line tools, you'll need to install Nodejs as a local development dependency.  The `npm` package manager comes bundled with all recent releases of Nodejs.

The link:/en/managing-client-tools.html[`rhc` command-line tool] makes it easy to link:/en/managing-creating-applications.html[provision new hosted application environments] - complete with DNS, ssh, and git services.

[[launch]]
== Step1: Create a Nodejs Application

To launch a new application named *myapp*, using the `nodejs-0.10` web runtime cartridge:
[source, console]
----
$ rhc app create myapp nodejs-0.10
----

OpenShift's default platform features include automatic DNS setup, SSH services, and a git server. The resulting output should contain a live URL where your application will be available:

[source]
----
https://MyApp-MyNamespace.rhcloud.com/
----

By default, the `rhc app create` command will also attempt to create a local git repository (for development use).  This repo will contain a `git remote` address that can be used to push updates to your site.

The output will look something like this:

[source, console]
----
Application Options
-------------------
Domain:     shifter
Cartridges: nodejs-0.10
Gear Size:  default
Scaling:    no

Creating application 'myapp' ... done


Waiting for your DNS name to be available ... done

Cloning into 'myapp'...
Warning: Permanently added the RSA host key for IP address '54.166.64.174' to the list of known hosts.

Your application 'myapp' is now available.

  URL:        http://myapp-shifter.rhcloud.com/ <1>
  SSH to:     54456e094382ec92df000251@myapp-shifter.rhcloud.com
  Git remote: ssh://54456e094382ec92df000251@myapp-shifter.rhcloud.com/~/git/myapp.git/
  Cloned to:  /home/ryanj/src/myapp <2>

Run 'rhc show-app myapp' for more details about your app.
----
<1> Public URL of application
<2> Location of local Git repository

The application will now be running and accessible at the *URL (1)* listed in the output. A local git repository for your application was also created in the directory listed under *Cloned to (2)*.

After creating your app, link:managing-modifying-applications.html[try publishing an update with `git push`], or link:/en/managing-adding-a-database.html[adding a database with `rhc cartridge add`].

== Advanced App Creation
Running `rhc help app create` provides an excellent reference of optional flags.  For example, the `--from-code` argument makes it easy to deploy existing projects, link:https://blog.openshift.com/run-your-nodejs-projects-on-openshift-in-two-simple-steps[as long as they've been adapted to run on OpenShift].

This command creates a new horizontally scalable "parks" application from an existing project repo, using the `nodejs-0.10` and `postgresql-9.2` cartridges as runtime dependencies, while setting an env variable named "FOO" to the value of "BAR" in the resulting system envonment:
[source]
----
$ rhc app create parks nodejs-0.10 postgresql-9.2 -s --from-code=https://github.com/ryanj/restify-postGIS.git FOO=BAR
----

OpenShift also provides link:https://blog.openshift.com/launching-applications-with-openshifts-web-based-workflow[browser-based workflows for launching new hosted environments right from the Web].

== Other Tips
Visit the link:/[OpenShift Developer Center] for more information about link:#top[getting started with Nodejs]:

=== link:/en/node-js-environment-variables.html[Environment Variables]
OpenShift's Nodejs cartridge uses the following system environment variables to publish router connection details, and to customize the application's build, hosting, and scaling routines:

[cols="1,3",options="header"]
|===
|Environment Variable | Use

|OPENSHIFT_NODEJS_IP
|Bind to this IP address in order to recieve traffic from the routing layer
|OPENSHIFT_NODEJS_PORT
|Listen on this port to recieve traffic from the routing layer
|OPENSHIFT_NODEJS_POLL_INTERVAL
|This integer value may be set as an environment variable (default is 1 second)
|NPM_CONFIG_PRODUCTION
|OpenShift will not install `devDependencies` link:http://stackoverflow.com/a/23749201/754025[when `NPM_CONFIG_PRODUCTION` is set to "true"]
|===

See the master index of link:/en/managing-environment-variables.html[Environment Variables] for more information.

[[markers]]
=== link:/en/node-js-project-structure.html#markers[Marker Files]
Marker files can be used to customize various aspects of the Nodejs build and deployment process.

Adding the following empty files to your project's `.openshift/markers` folder allows you to customize the runtime experience:

[cols="1,3",options="header"]
|===
|Marker File | Effect

|hot_deploy
|Push code updates without waiting for a full application restart. link:/en/managing-modifying-applications.html#_hot_deployment_build_details[This feature] is not available when the `use_npm` marker is enabled.
|use_npm
|Initialize your application or service using `npm start` instead of `supervisor servername.js` (where `servername.js` is based on the value of your `package.json`'s `main` attribute).
|===

== Next Steps

The best next step is to link:#launch[create an application] using OpenShift.

Look at the https://www.openshift.com/application-gallery[application gallery] and https://www.openshift.com/developer-spotlight[developer spotlight] to see what other developers have created on OpenShift.

Browse our http://origin.ly/[quickstarts and community cartridges] to see other exciting technology you can use in your applications.

Finally, if at any point you have questions or issues, please visit the link:https://help.openshift.com/hc/en-us[OpenShift Online Help Center] for a full list of options.
