---
layout: base
category: 01_Overview
breadcrumb: Overview
parent_url: overview-what-is-openshift.html
nav_title: What is OpenShift?
nav_priority: 1
meta_desc: OpenShift Online is Red Hats public cloud application development and hosting platform that automates the provisioning, management and scaling of applications.
---
= What is OpenShift?

[float]
= What is OpenShift? 
[.lead]
OpenShift Online is Red Hat's public cloud application development and hosting platform that automates the provisioning, management and scaling of applications so that you can focus on writing the code for your business, startup, or big idea.

video::aZ40GobvA1c[youtube, width=450, height=253]

== OpenShift Runtime Environments
OpenShift Online supports a variety of technologies through use of cartridges, including *Java* (Wildfly, JBossEAP, Tomcat), *PHP*, *Node.js*, *Python*, *Perl*, *MySQL*, *PostgreSQL*, *MongoDB*, *Jenkins*, *Cron*, and *JBoss xPaaS Services* (Fuse, BPM Suite, BRMS, Data Virtualization, Aerogear, and more).

link:languages-overview.html[-> Learn More About OpenShift Cartridges]

== The OpenShift Development Environment
There are a number of tools that can enhance your OpenShift experience and match your style of development. From command line scripts that you can use to automate tasks to the Web Console and even a fully integrated IDE. Below are links to a number of these tools along with getting started guides and other helpful documents to get you up and running fast.

=== Web Console
An easy to use resource for managing your applications from anywhere. You can create applications, add and remove cartridges and edit account details.

link:https://openshift.redhat.com/app/console[-> Access the Web Console]

=== RHC Client Tools
The OpenShift client tools make it easy to create and deploy applications, manage domains, control access to your OpenShift applications, and give you complete control of your cloud environment.

link:getting-started-client-tools.html[-> Install and Use RHC]

=== JBoss Developer Studio
JBoss Developer Studio, with its Eclipse Based integrated development environment, gives developers everything they need to build rich web applications and transactional enterprise applications. Integrates with the OpenShift platform to put the ability to create, edit and deploy applications right at your fingertips.

link:getting-started-installing-jboss-studio.html[-> Install and Use JBoss Developer Studio]

== Pricing and Premium Features
OpenShift Online currently offers several options to developers, including a pretty generous free tier. Please visit our link:https://www.openshift.com/products/pricing[pricing page] for more information.

Interested in learning more about OpenShift's premium features? Visit our link:overview-platform-features.html[features guide] for more information.

== Get Started with OpenShift Online
Ready to launch your big idea on OpenShift? link:getting-started-overview.html[Get started] now!

Visit our link:https://help.openshift.com[Help Center] if you have any questions along the way.
