---
layout: base
category: 01_Overview
breadcrumb: Overview
parent_url:
nav_title: Client Tools
nav_priority: 50
---
= Client Tools

== Client Tools
The OpenShift Client tools, known as rhc, are built and packaged using the Ruby programming language. OpenShift integrates with the Git version control system to provide powerful, decentralized version control for your application source code.

OpenShift rhc can be run on any operating system with Ruby 1.8.7 or higher assuming you have the requisite user permissions to install programs. Instructions for specific operating systems are provided below. It is assumed that you are running the commands from a command line window, such as Command Prompt, or Terminal. 

If you are using link:#rvm[Ruby
Version Manager (rvm) see the instructions below].

[[windows]]
Windows
~~~~~~~~

http://rubyinstaller.org[RubyInstaller 1.9] provides the best experience
for installing Ruby on Windows XP, Vista, and Windows 7. Download the
newest version from http://rubyinstaller.org/downloads/[the download
page] and launch the installer.

*Important*: During the installation you can accept all of the defaults,
but it is mandatory that you select the "Add Ruby executables to your
PATH" check box in order to run Ruby from the command line.

After the installation is completed, to verify that the installation is
working run:
----
C:Files> ruby -e 'puts "Welcome to Ruby"' Welcome to Ruby
----
If the 'Welcome to Ruby' message does not display, the Ruby
executable may not have been added to the path. Restart the installation
process and ensure the "Add Ruby executables to your PATH" check box is
selected.

[[installing-git]]
Installing Git
^^^^^^^^^^^^^^

The next step is to install http://msysgit.github.com/[Git for Windows]
so that you can synchronise your local application source and your
OpenShift application. Git for Windows offers the easiest Git experience
on the Windows operating system and is the recommended default - if you
use another version of Git please ensure it can be executed from the
command line and continue to the next section.

Download and install the
http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git[latest
version of Git for Windows]. Ensure that Git is added to your PATH so
that it can be run from the command line. After the installation is
completed, to verify that Git is correctly configured run:
----
C:Files> git --version git version 1.7.11.msysgit.1
----

[[installing-the-openshift-gem]]
Installing the OpenShift gem
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

After Ruby and Git are correctly installed, use the RubyGems package
manager (included in Ruby) to install the OpenShift client tools. Run:

------------------------
C:Files> gem install rhc
------------------------

RubyGems downloads and installs the rhc gem from
http://rubygems.org/gems/rhc[www.rubygems.org/gems/rhc]. The
installation typically proceeds without errors. After installation is
complete, run:

------------------------
C:Files> rhc setup
------------------------
The OpenShift interactive setup wizard displays and prompts you to complete the rest
of the process. If you cannot run OpenShift client tools at this point,
please contact us on
http://webchat.freenode.net/?channels=openshift&uio=d4[IRC] or post in
link:/forums/openshift[our forums] for more assistance.

video::cgNWp7SlS3A[youtube, width=640, height=480]

[[mac-os-x]]
Mac OS X
~~~~~~~~~

From OS X Lion onwards, Ruby 1.8.7 is installed by default. On older Mac
systems, Ruby is shipped as part of the
http://developer.apple.com/xcode[Xcode development suite] and can be
installed from your installation CD. If you are familiar with Mac
development, you can also use http://macruby.org/[MacRuby] or see the
http://www.ruby-lang.org/en/downloads/[Ruby installation page for help
installing with homebrew].

To verify that Ruby is correctly installed run:

----------------------------------
$ ruby -e 'puts "Welcome to Ruby"'
Welcome to Ruby
----------------------------------

There are a number of options on Mac OS X for Git. We recommend the
http://code.google.com/p/git-osx-installer/[Git for OS X installer] -
download and run the latest version of the dmg file on your system. To
verify the Git for OS X installation, run:

--------------------
$ git --version
git version 1.7.11.1
--------------------

With Ruby and Git installed, use the RubyGems library system to install
and run the OpenShift gem. Run:

----------------------
$ sudo gem install rhc
----------------------

After the installation is complete, run:

-----------
$ rhc setup
-----------

The OpenShift interactive setup wizard displays and prompts you to
complete the rest of the process. If you cannot run the OpenShift Client
tools at this point, please contact us on
http://webchat.freenode.net/?channels=openshift&uio=d4[IRC] or post in
link:/forums/openshift[our forums] for more assistance.

video::MoGpT1AW3MA[youtube, width=640, height=480]

[[fedora]]
Fedora
~~~~~~

RHC client tools are available as an RPM and can be installed with the
YUM package manager on Fedora. Keep in mind that this version is not
updated as frequently as the the Ruby gem version.

To install using yum on Fedora:

------------------------------
$ sudo yum install rubygem-rhc
------------------------------

This installs Ruby, Git, and the other dependencies required to run the
OpenShift client tools..

After the rhc client tools are installed, run:

-----------
$ rhc setup
-----------

The OpenShift interactive setup wizard displays and prompts you to
complete the rest of the process. If you cannot run the OpenShift client
tools at this point, please contact us on
http://webchat.freenode.net/?channels=openshift&uio=d4[IRC] or post in
link:/forums/openshift[our forums] for more assistance.

To update the OpenShift client tools to the latest version provided by
the OpenShift team outside of yum, run:

---------------------
$ sudo gem update rhc
---------------------

The most recent version is downloaded and updated.

[[red-hat-enterprise-linux-6]]
Red Hat Enterprise Linux 6
~~~~~~~~~~~~~~~~~~~~~~~~~~~

We recommend using the Ruby gem on RHEL. You need to install rubygems
and git first with:

-------------------------------
$ sudo yum install rubygems git
-------------------------------

In order to install the rubygems package the RHEL Optional channel must
be enabled. There are two ways of doing this from the command line:

-----------------------------------------------------------------
# If you are using the Certificate-Based RHN tooling
$ sudo yum-config-manager --enable rhel-6-server-optional-rpms   

# If you are using RHN-Classic
$ sudo rhn-channel --add --channel=rhel-x86_64-server-optional-6
-----------------------------------------------------------------

With the repository in place, you can now install the OpenShift client
tools. Run:

----------------------
$ sudo gem install rhc
----------------------

To update the OpenShift client tools to the latest version run:

---------------------
$ sudo gem update rhc
---------------------

After OpenShift client tools are installed, run:

-----------
$ rhc setup
-----------

The OpenShift interactive setup wizard displays and prompts you to
complete the rest of the process. If you cannot run the OpenShift client
tools at this point, please contact us on
http://webchat.freenode.net/?channels=openshift&uio=d4[IRC] or post in
link:/forums/openshift[our forums] for more assistance.

[[ubuntu]]
Ubuntu
~~~~~~~

Use the apt-get command line package manager to install Ruby and Git
before you install the OpenShift command line tools. Run:

--------------------------------------------------
$ sudo apt-get install ruby-full rubygems git-core
--------------------------------------------------

After you install both Ruby and Git, verify they can be accessed via the
command line:

----------------------------------
$ ruby -e 'puts "Welcome to Ruby"'
Welcome to Ruby
$ git --version
git version 1.7.11.1
----------------------------------

If either program is not available from the command line, please add
them to your PATH.

With Ruby and Git correctly installed, you can now use the RubyGems
package manager to install the OpenShift client tools. From a command
line, run:

----------------------
$ sudo gem install rhc
----------------------

If you are using an Ubuntu 11.10 or older (and derivates such as Mint)
and are using the system Ruby, you may see errors related to invalid
date formats when installing the OpenShift client tools gem. You may
need to run the following commands before doing the gem install rhc
command:

-----------------------------------
$ sudo gem install rubygems-update 
$ sudo update_rubygems
-----------------------------------

Read more about https://github.com/rubygems/rubygems/pull/57[this
problem and its symptoms].

After the OpenShift client tools are installed, run:

-----------
$ rhc setup
-----------

The OpenShift interactive setup wizard displays and prompts you to
complete the rest of the process. If you cannot run the OpenShift client
tools at this point, please contact us on
http://webchat.freenode.net/?channels=openshift&uio=d4[IRC] or post in
link:/forums/openshift[our forums] for more assistance.

video::WZug3f-Ld34[youtube, width=640, height=480]

[[ruby-version-manager]]
Ruby Version Manager
~~~~~~~~~~~~~~~~~~~~~

Ruby Version Manager allows you to install and run multiple versions of
Ruby. When installing the OpenShift client tools gem onto a system with
RVM, you need to install the gem to the global gemset, making it
available to all versions of Ruby.

-----------------------
$ rvm gemset use global
$ gem install rhc
-----------------------

No matter which version of Ruby you are running, the rhc command will be
available.

[[staying-current]]
Staying Current
~~~~~~~~~~~~~~~~

Once you've installed the rhc gem, it's very easy to update. Ruby
includes a built in mechanism for updating libraries. Just run:

----------------
$ gem update rhc
----------------

or

---------------------
$ sudo gem update rhc
---------------------

and you'll get the latest version of the tools. Be sure to check your
specific Operating System instructions above if you have any problems.

[[other-sources-of-reference-material]]
Other sources of reference material
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more help see our link:/developers/get-help[Get Help] page.

Check out the link:/docs-client-tools[detailed installation guide for
RHC client tools].
