---
layout: base
category: 30_Perl
breadcrumb: Perl
parent_url: perl-overview.html
nav_title: Overview
nav_priority: 1
---
= Perl Overview
:source-highlighter: coderay

[[top]]
[[perl-application-hosting]]
== Perl Application Hosting

Perl is a high-level, general-purpose dynamic programming language. With OpenShift you can easily deploy and run Perl applications using your favorite frameworks and databases. Want a Dancer application backed by MySQL? Or maybe you're looking for Mojolicious and MongoDB? If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift.

[[simplify-the-lifecycle]]
== Simplify the Lifecycle

Getting a Perl app with a MySQL backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp perl-5.10
$ rhc cartridge add mysql-5.5 -a MyApp
--

These two commands create your "server" and install and configure Perl, MySQL, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

== End-to-End Perl Support

Looking to scale your Perl application for heavy traffic, or want to automatically build/test/deploy? We've got you covered there too!

[cols="2*"]
|===
|Application Stack
a|* https://github.com/openshift/dancer-example[Dancer] 
* Catalyst 
* CGI::Application 
* Mojolicious 

|Datastores
a|* link:/developers/mysql[MySQL]
* link:/developers/mongodb[MongoDB] 
* link:/developers/postgresql[PostgreSQL]

|Tools
a|* link:/blogs/getting-started-with-eclipse-paas-integration[Eclipse]
* link:/blogs/getting-started-with-eclipse-paas-integration[JBoss Tools]
* link:/blogs/look-ma-no-hands-developing-for-the-cloud-in-the-cloud-with-cloud9-ide[Cloud9 IDE] 
* link:/developers/deploying-and-building-applications[Git] 
* link:/developers/remote-access/[SSH Access] 
* link:/jenkins[Jenkins]
|===

