---
layout: base
category: 10_PHP
breadcrumb: PHP
parent_url: php-overview.html
nav_title: Overview
nav_priority: 1
---
= PHP Overview
:source-highlighter: coderay
:icons:

[[top]]
[[php-application-hosting]]
== PHP Application Hosting

With OpenShift you can easily deploy and run PHP applications using your favorite frameworks and databases. Want a Zend server backed by MySQL? Or maybe you're looking for CodeIgniter and MongoDB? If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift.

NOTE: PHP is a general-purpose server-side scripting language originally designed for Web development to produce dynamic Web pages. -> link:http://php.net/[Learn more]

link:#simplify-your-php-deployments[Simplify your PHP deployments] +
link:#go-enterprise-with-zend[Go Enterprise with Zend] +
link:#environment-variables[Environment variables] +
link:#end-to-end-php-support[End-to-End PHP Support] +
link:#rapid-development-with-ide[Rapid Development with an IDE] +
link:#build-test-deploy[Build -> Test -> Deploy] +
link:#scale-to-meet-your-needs[Scale to Meet Your Needs] +

[[simplify-your-php-deployments]]
== Simplify your PHP deployments

Getting a PHP app with a MySQL backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp php-5.4
$ rhc cartridge add mysql-5.5 -a MyApp
--

These two commands create your "server" and install and configure PHP, MySQL, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

As MySQL was deployed for you by the platform, you can connect to it by using connection parameters exposed in the environment variables.

link:#top[Back to Top]

[[go-enterprise-with-zend]]
== Go Enterprise with Zend

include::_fragments/php-zend-overview.adoc[]

include::_fragments/php-zend-deploy.adoc[]

IMPORTANT: link:php-zend.html[Learn More about Zend Server]

link:#top[Back to Top]

[[environment-variables]]
== Environment variables

include::_fragments/php-env.adoc[]

link:#top[Back to Top]

[[end-to-end-php-support]]
== End-to-End PHP Support

Looking to scale your PHP application for heavy traffic, or want to automatically build/test/deploy? We've got you covered there too!

=== Stacks

* link:php-zend.html[Zend Server]

=== Tools

* link:php-composer.html[Composer]

=== Frameworks

* link:php-cakephp.html[CakePHP]
* link:php-codeigniter.html[CodeIgniter]
* link:php-symphony.html[Symphony]
* link:php-yii.html[Yii]
* link:php-zend.html[Zend Framework]

=== Applications

* link:php-drupal.html[Drupal]
* link:php-magento.html[Magento]
* link:php-wordpress.html[Wordpress]

link:#top[Back to Top]

[[rapid-development-with-ide]]
== Rapid Development with an IDE

How you develop your PHP application is up to you. Use your favorite IDE and track and push your changes with Git. But you dislike command line?

For a seamless development experience on OpenShift, use the link:php-jboss.html[JBoss Tools with Eclipse] to deploy your changes to the cloud, tail application log files, and connect to remote databases.

Don't like the command line? No problem! Use the  to create and work with your applications.

-> link:php-jboss.html[Install the JBoss Tools]

link:#top[Back to Top]

[[build-test-deploy]]
== Build -> Test -> Deploy

Want to make sure your PHP application is stable before your latest changes go live?

link:https://wiki.jenkins-ci.org[Jenkins] is a full featured continuous integration (CI) server that can run builds, tests, and other scheduled tasks and integrate with your OpenShift applications.

-> link:php-jenkins.html[Build with Jenkins]

link:#top[Back to Top]

[[scale-to-meet-your-needs]]
== Scale to Meet Your Needs

Enable your application to react to changes in traffic and automatically allocate the necessary resources to handle your current demand.

The OpenShift infrastructure monitors incoming web traffic and automatically brings copies of your web cartridge on-line to handle requests.

-> link:php-scaling.html[Scale your application]

link:#top[Back to Top]
