---
layout: php
category:
breadcrumb: Languages and Technologies
parent_url: languages-overview.html
nav_title: Framework - Laravel
nav_priority: 50
meta_desc: PHP developers - Deploying Laravel on OpenShift
---
= Laravel PHP Framework on OpenShift

[float]
= Deploying the Laravel PHP Framework on OpenShift

Laravel is a one of the younger PHP frameworks and has recently become much more popular. Built on link:http://symfony.com[Symphony] components, it inherits a proven codebase, but gives developers a new way of writing PHP applications.

IMPORTANT: This purpose of this tutorial is not to teach Laravel as a framework. To do that, you should follow the link:http://laravel.com/docs/4.2[official documentation]. This tutorial expects you to be familiar with Laravel and to already have an application you want to deploy on OpenShift.

== Connecting to a Database
Configure the database configuration file `app/config/database.php` to integrate with OpenShift using the appropriate link:managing-environment-variables.html[environment variables].

For example, if using MySQL:

[source,php]
----
'mysql' => array(
    'host' => getenv('OPENSHIFT_MYSQL_DB_HOST'),
    'port' => getenv('OPENSHIFT_MYSQL_DB_PORT'),
    'driver'    => 'mysql',
    'database'  => getenv('OPENSHIFT_APP_NAME'),
    'username'  => getenv('OPENSHIFT_MYSQL_DB_USERNAME'),
    'password'  => getenv('OPENSHIFT_MYSQL_DB_PASSWORD'),
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
),
----

Similarly you can configure your application to connect to other databases.

link:http://localhost:4242/en/managing-adding-a-database.html[-> Read more about managing databases on OpenShift]
