Main Header
===========
:Author:    Shawn Purtell
:Email:     spurtell@redhat.com
:Date:      2014-07-19
:Revision:  1.0
:source-highlighter: coderay
:awestruct-layout: php

== PHP Application Hosting

PHP is a general-purpose server-side scripting language originally designed for Web development to produce dynamic Web pages.

=== Overview

With OpenShift you can easily deploy and run PHP applications using your favorite frameworks and databases. Want a Zend server backed by MySQL? Or maybe you're looking for CodeIgniter and MongoDB? If it can run on Red Hat Enterprise Linux 64bit, then it can run on OpenShift.

=== Simplify the Lifecycle

Getting a PHP app with a MySQL backend deployed onto OpenShift is as easy as executing two commands:

[source]
--
$ rhc app create MyApp php-5.4
$ rhc cartridge add mysql-5.5 -a MyApp
--

These two commands create your "server" and install and configure PHP, MySQL, and a git repository on the server. You can now visit your application on the web at:

[source]
--
http://MyApp-MyDomain.rhcloud.com/
--

=== End-to-End PHP Support

Looking to scale your PHP application for heavy traffic, or want to automatically build/test/deploy? We've got you covered there too!

==== Stacks

* link:php-zend.html[Zend Server]

==== Tools

* link:php-composer.html[Composer]

==== Frameworks

* link:php-cakephp.html[CakePHP]
* link:php-codeigniter.html[CodeIgniter]
* link:php-symphony.html[Symphony]
* link:php-yii.html[Yii]
* link:php-zend.html[Zend Framework]

==== Applications

* link:php-drupal.html[Drupal]
* link:php-magento.html[Magento]
* link:php-wordpress.html[Wordpress]

=== Rapid Development with an IDE

How you develop your PHP application is up to you. Use your favorite IDE and track and push your changes with Git. But you dislike command line?

For a seamless development experience on OpenShift, use the link:php-jboss.html[JBoss Tools with Eclipse] to deploy your changes to the cloud, tail application log files, and connect to remote databases.

Don't like the command line? No problem! Use the  to create and work with your applications.

=> link:php-jboss.html[Install the JBoss Tools]

=== Build -> Test -> Deploy

Want to make sure your PHP application is stable before your latest changes go live?

link:https://wiki.jenkins-ci.org[Jenkins] is a full featured continuous integration (CI) server that can run builds, tests, and other scheduled tasks and integrate with your OpenShift applications.

=> link:php-jenkins.html[Build with Jenkins]

=== Scale to Meet Your Needs

Enable your application to react to changes in traffic and automatically allocate the necessary resources to handle your current demand.

The OpenShift infrastructure monitors incoming web traffic and automatically brings copies of your web cartridge online to handle requests.

=> link:php-scaling.html[Scale your application]

'''
Content last updated {date}
