---
layout: python
category:
breadcrumb: Languages and Technologies
parent_url: python-overview.html
nav_title: Getting Started
nav_priority: 10
meta_desc: Get started with Python 2.6, 2.7, or 3.3 on OpenShift.
---

= Getting Started

[[top]]
[float]
= Getting Started with Python 2.6, 2.7, and 3.3

By default, OpenShift comes with all 3 versions of Python and the pattern of building and deploying applications is the same for all three. The Python cartridges are based on a link:http://en.wikipedia.org/wiki/Web_Server_Gateway_Interface[WSGI server model] of Python web creation. 
This tutorial will start with showing you how to create an application using the default, Apache with Mod_WSGI, but it will also show you to use link:http://gunicorn.org/[Gunicorn] as an example of using a different WSGI server.

link:#step1[Step 1: Create a Tomcat Application] + 
link:#step2[Step 2: Make the First Change] +
// TODO link:#step3[Step 3: Using a Different Server than Mod_WSGI] +
// TODO link:#other[Other Tips] +
// TODO link:#next[Next Steps]  

[[step1]]
== Step 1: Create a Python Application

This tutorial walks through the creation of an application titled *mypythonapp* under the domain *mydomain*. We will use Python 2.7 but you can substitute in Python 2.6 or 3.3 and use them in the same way. Before going through the rest of the tutorial, make sure to have link:https://www.openshift.com/app/account[created an OpenShift account] and link:getting-started-client-tools.html[installed the RHC command line tools].  

Once that is completed, open a terminal on a local machine and change into a directory where the source code will be located.  Then at the command prompt enter the follwing command to create a Python application:

[source, console]
--
$ rhc app-create mypythonapp python-2.7
--

The output will look something like this:

[source, console]
--
Application Options
-------------------
Domain:     mydomain
Cartridges: python-2.7
Gear Size:  default
Scaling:    no

Creating application 'mypythonapp' ... done


Waiting for your DNS name to be available ... done

Cloning into 'mypythonapp'...
Warning: Permanently added 'mypythonapp-mydomain.rhcloud.com,54.0.0.218' (RSA) to the list of known hosts.

Your application 'mypythonapp' is now available.

  URL:        http://mypythonapp-mydomain.rhcloud.com/ <1>
  SSH to:     541a13a04382ec00000002f3@mypythonapp-mydomain.rhcloud.com
  Git remote: ssh://541a13a04382ec00000002f3@mypythonapp-mydomain.rhcloud.com/~/git/mypythonapp.git/ 
  Cloned to:  /home/me/git_demo/mypythonapp <2>

Run 'rhc show-app mypythonapp' for more details about your app.
--
<1> Public URL of application
<2> Location of local Git repository

The application will now be running and accessible at the *URL (1)* listed in the output. A local git repository for your application was also created in the directory listed under *Cloned to (2)*.

link:#top[Back to Top]

[[step2]]
== Step 2: Make the First Change
A developer on OpenShift can make code changes on a local machine, check those changes in locally, and then `push` those changes to OpenShift. One of the primary advantages of Git is that it does not require a continuous online presence in order to run. A developer can easily check in (in Git terminology, `commit`) and revert changes locally before deciding to upload those changes to OpenShift.

=== Using the Git Repository

To make the first change, edit `wsgi.py` in the base of the local git repository. Go to the file in the terminal and edit with a comand line editor like *VIM* or *EMacs*. Alternatively, edit the file using any text editor or IDE. The beginning of this file starts a basic WSGI application with some URL routing. Strip out everything between the two `<body>` tags and change the content to look like this:

[source, html]
--
<body>
	<h1>Hello world!</h1>
</body>
--

Now that you have made this incredibly complicated code change, the code must be deployed to the server. Accomplish this task using *Git*.

. First `commit` our local changes to the git repository and include a message for the commit:
+
[source, console]
--
$ git commit -a -m "code ninja skillz"
--
+
. Finally, `push` these changes to the remote OpenShift application.
+
[source, console]
--
$ git push
--

NOTE: If any new files were added to your local repo, the use the git  `add --all` command to track new files as part of the repository:
[source, console]
--
$ git add --all .
--


The output of the push command will first show the git push and then the build process and deployment for the OpenShift application. When the build is finished, go back to the application's URL (_mypythonapp-mydomain.rhcloud.com_) and see a page which just says "Hello World" in nice big font.

This is the basic process to follow when developing an application: `git add` (optional), code change, `git commit`, and finally `git push`.

If you are curious about Git or would like to learn more, the link:http://git-scm.com/book[Pro Git book] is a great resource.

link:#top[Back to Top]

