---
layout: python
category:
breadcrumb: Languages and Technologies
parent_url: python-overview.html
nav_title: Deployment Options
nav_priority: 30
meta_desc: Python developers - OpenShift Online Python 2.6, 2.7, & 3.3 cartridge deployment options
---

= Python Deployment Information

[float]
= Python Deployment Information


== Application Dependencies

OpenShift uses link:https://pypi.python.org/pypi/pip[pip] along with link:http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtualenvs] to install and manage packages required for your application. There are two files you can use to declare the packages your Python application depends upon. 

1. setup.py - this file is used by distutils to link:https://docs.python.org/2/distutils/setupscript.html[specify metadata and package dependencies] for your application. By default, OpenShift uses this file to manage Python dependencies. This file will be placed in the base of your git repository with some basic information filled in. Please note you are *not* required to add the following header to your setup.py file. 

[source, python]
--

#!/usr/bin/env python

from distutils.core import setup

--

2. requirements.txt = this file is used with **pip install** to install any packages required for your application. This file is also located in the root of your git repository.  There is link:https://pip.readthedocs.org/en/1.1/requirements.html[good documentation] on the format and benefits of the requirements.txt file. One of the big advantages of using a requirements file is you can have **pip** generate the requirements.txt with the following command:

[source, console]
--
 pip freeze > stable-req.txt
--


NOTE: you can use both setup.py and requirements.txt in your application but then you will have to manage any conflicts different versions of the same package installed in your application.

== Using a different WSGI server other than Mod_WSGI

OpenShift offers the ability to use a different WSGI server other than the default, which is Mod_WSGI. To enable a different WSGI server, all you need to do is a place an **app.py** file in the base of the OpenShift git respository. Here is a link:https://github.com/openshift-quickstart/Bottle-Python3-quickstart/blob/master/app.py[little example] that uses the WSGI reference implementation to start a new server. 

NOTE: On OpenShift, you should use the link:managing-environment-variables.html[environment variables] for port and IP when you start up your WSGI server. 

