---
title: Overview
description: An overview of addon guides on OpenShift.
---

[[top]]
[float]
= Overview of Add-on Guides
[.lead]
OpenShift Online offers a numbers of addons to help you quickly add additional functionality to your application.

== Database Services
link:#phpmyadmin[phpMyAdmin] +
link:#rockmongo[RockMongo] +

[[phpmyadmin]]
=== phpMyAdmin
phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web. phpMyAdmin supports a wide range of operations on MySQL, MariaDB and Drizzle. Frequently used operations (managing databases, tables, columns, relations, indexes, users, permissions, etc) can be performed via the user interface, while you still have the ability to directly execute any SQL statement. +
link:/core-addons/phpmyadmin.html[-> Learn More]

[[rockmongo]]
=== RockMongo
phpMyAdmin is an open source MongoDB administration tool written in PHP, similarly to the phpMyAdmin, intended to handle administration of your MongoDB via auser-friendly web interface. +
link:/core-addons/rockmongo.html[-> Learn More]
