[[windows]]
== Setting up the OpenShift Environment on Windows
The command line environment requires three things to be installed on Windows: *Ruby*, *Git*, and *the rhc gem* (OpenShift command line tools gem)

=== Step 1 - Install Ruby
link:http://rubyinstaller.org[RubyInstaller 1.9] provides the best experience for installing Ruby on Windows XP, Vista, and Windows 7. Download the newest version from link:http://rubyinstaller.org/downloads/[the download page] and launch the installer.

IMPORTANT: During the installation you can accept all of the defaults, but it is mandatory that you select the *Add Ruby executables to your PATH* check box in order to run Ruby from the command line.

After the installation is completed, to verify that the installation is working run:
[source]
----
C:Files> ruby -e 'puts "Welcome to Ruby"' Welcome to Ruby
----
If the *Welcome to Ruby* message does not display, the Ruby executable may not have been added to the path. Restart the installation process and ensure the *Add Ruby executables to your PATH* check box is selected.

[[installing-git]]
=== Step 2 - Install Git
The next step is to install link:http://msysgit.github.com/[Git for Windows] so that you can synchronise your local application source and your OpenShift application. Git for Windows offers the easiest Git experience on the Windows operating system and is the recommended default - if you use another version of Git please ensure it can be executed from the command line and continue to the next section.

Download and install the link:http://msysgit.github.io/[latest version of Git for Windows]. *Make sure that Git is added to your PATH* so that it can be run from the command line. After the installation is completed, to verify that Git is correctly configured run:
[source]
----
C:Files> git --version git version 1.7.11.msysgit.1
----

[[installing-the-openshift-gem]]
=== Step 3: Install the OpenShift gem
After Ruby and Git are correctly installed, use the RubyGems package
manager (included in Ruby) to install the OpenShift client tools. Run:
[source]
----
C:Files> gem install rhc
----

RubyGems downloads and installs the rhc gem from link:http://rubygems.org/gems/rhc[www.rubygems.org/gems/rhc]. After installation is complete, run:
[source]
----
C:Files> rhc setup
----
The OpenShift interactive setup wizard displays and prompts you to complete the rest of the process. If you cannot run OpenShift client tools at this point, please visit the link:https://help.openshift.com[Help Center] for more assistance.

== Video Walkthrough
video::cgNWp7SlS3A[youtube, width=640, height=480]
