---

category:


title: Repository Layout

description: Node.js Project Structure Repository Layout
---
= Node.js Repository Layout

[float]
= Node.js Repository Layout
Nodejs applications should include the following basic project structure:

[source]
----
server.js                The default server script name
package.json             Npm package descriptor: dependency list, init config
node_modules/            Locally bundled module dependencies (Recommended)
.openshift/              OpenShift-specific files (Optional)
    markers/             OpenShift configuration flags, see the "Markers" list <1>
    action_hooks/        Custom build scripts, see the "Action Hooks" documentation <2>
----

<1> link:/languages/nodejs/markers.html[Node.js marker files]
<2> See the link:/managing-your-applications/action-hooks.html[action_hooks documentation] for detailed usage notes.

[[server.js]]
== `server.js`
By default, OpenShift and npm both look for a file named `server.js` to initialize your application.  You can specify an alternate server filename by link:#package.json[configuring the `main` and `scripts.start` sections of your `package.json` file].

You'll need to link:/languages/nodejs/environment-variables.html#listen[include a small check to test for the presence of environment variables] that are commonly link:/languages/nodejs/environment-variables.html[published by the `nodejs` cartridge]:

[source,javascript]
----
var server_port = process.env.OPENSHIFT_NODEJS_PORT || 8080
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1'

server.listen(server_port, server_ip_address, function(){
  console.log("Listening on " + server_ip_address + ", server_port " + server_port)
});
----

The above code provides sensible default values that will allow the application to run in local development environments, while taking advantage of link:/languages/nodejs/environment-variables.html[OpenShift-provided configuration details when they are available].

[[package.json]]
== `package.json`
Every nodejs application should include a `package.json` file to document the project's link:https://blog.openshift.com/run-your-nodejs-projects-on-openshift-in-two-simple-steps#package_json[init process] and  link:/languages/nodejs/dependency-management.html[list of dependencies].

Make sure that the link:https://www.npmjs.org/doc/misc/npm-scripts.html#DEFAULT-VALUES[`scripts.start`] and link:https://www.npmjs.org/doc/json.html#main[`main`] sections of your `package.json` file contain accurate information on how to start your project:

[source,json]
----
"scripts": {
  "start": "supervisor server.js"
},
"main": "server.js"
----

Check the link:/languages/nodejs/markers.html[Markers] section for specifics on how OpenShift uses this information to manage your server.

[[node_modules]]
== `node_modules`

Npm module dependencies are cached locally within this folder.
OpenShift can generate this folder's contents automatically by running `npm install` during your project's build process.  Tracking the contents of this folder with `git` can help make deployments easier to audit, and it allows OpenShift to use the cached modules to speed up your build process.

NOTE: The `deplist.txt` file was previously used to document an application's dependency list.  The standard `package.json` file should be used instead. See link:/languages/nodejs/dependency-management.html[Dependency Management with NPM].
