---




title: cine.io

description: Using cine.io as an external service for your OpenShift applications.
---
= cine.io External Add-on Service

[float]
= cine.io

[.lead]
Cine.io is the first video live-streaming service built by and for developers. Using either our REST API or pre-packaged SDKs for iOS, Android, or the web, developers can, with just a few lines of code, integrate live video into their applications. The service includes a global, blazing-fast CDN with more than 2,000 interconnected networks on 5 continents. There are no account minimums, and it's free to get started.

link:#dashboard[Dashboard] +
link:#integration[Integrating the Service With Your App] +
link:#resources[Additional Resources] +
link:#support[Support]

[[dashboard]]
== Dashboard
The cine.io dashboard can be accessed by visiting: link:https://www.cine.io/[www.cine.io]

[[integration]]
== Integrating the Service With Your App
Once you have link:/external-services/index.html#subscribe-service[subscribed to this service] and link:/external-services/index.html#locate-credentials[located your credentials], you will need to configure your application to use the credentials for your service.

=== Cine.io Environment Variables
We recommend setting the following environment variables within your application runtime to connect the service to your app:

|===
|Variable Name|Example Value
|CINE_IO_PUBLICKEY|20828c32664812b70f1f0779b575c5e9
|CINE_IO_SECRETKEY|f4a8410043e38bdq90j4be5ec0b677ee
|===

Use the link:/managing-your-applications/client-tools.html[OpenShift client tools] to set environment variables to make your credentials available within your application runtime:

[source,console]
----
$ rhc env set CINE_IO_PUBLICKEY=VALUE -a App_Name
$ rhc env set CINE_IO_SECRETKEY=VALUE -a App_Name
----

To start using cine.io in your application, import the appropriate cine.io SDK and use it with the Public and Secret keys that are available in the environment variables listed above.

NOTE: Check out the general link:/external-services/index.html#code-examples[code examples] to see how to use environment variables within your application.

[[resources]]
== Additional Resources
Additional documentation is available at link:http://developer.cine.io/[http://developer.cine.io/].

[[support]]
== Support

Email:: support@cine.io
Knowledgebase:: cineio.uservoice.com