---




title: DreamFactory

description: Using DreamFactory as an external service for your OpenShift applications.
---
= DreamFactory

[float]


[.lead]
DreamFactory is an open source REST API platform for mobile enterprise and web application developers. DreamFactory connects any data source to any mobile device with a comprehensive palette of RESTful services. Data sources include SQL databases, NoSQL document stores, file storage systems, and external web services.

link:#integration[Integrating the Service With Your App] +
link:#resources[Additional Resources] +
link:#support[Support]

[[integration]]
== Integrating the Service With Your App
There is no need to set environment variables within your application to use this service. 

[[resources]]
== Additional Resources
Installation instructions are available at link:https://github.com/dreamfactorysoftware/dsp-core/wiki/Deploying-to-OpenShift[https://github.com/dreamfactorysoftware/dsp-core/wiki/Deploying-to-OpenShift].

[[support]]
== Support
We offer excellent link:http://www.dreamfactory.com/pricing/support[paid product support] packages and a commercial license for interested customers. For other assistance, we provide a variety of ways to contact our Customer Success team, below.

Call:: 1-888-399-DREAM (3732) Option 2
Email:: link:mailto:support@dreamfactory.com[support@dreamfactory.com]
Live Chat:: link:http://beta.mycontactual.com/SC/chat.php?tenant=dreamfactory&sc_name=DreamFactory+Support+Center&referrer=Website[Support Center]
File Bug Report:: link:http://github.com/dreamfactorysoftware/dsp-core/wiki/File-a-Ticket-on-GitHub[GitHub Ticket]
Complete Documentation:: link:http://github.com/dreamfactorysoftware/dsp-core/wiki[GitHub Wiki]
Discourse Forum:: link:http://community.dreamfactory.com/[DreamFactory Community]
Twitter Support:: link:http://twitter.com/dfsoftwareinc/[@dfsoftwareinc]