---
layout: base
category: 
breadcrumb: Getting Started
parent_url:
nav_title: Hot Deploying Code
nav_priority: 20
---
= Hot-Deploying Code

By default, Git pushing code to an application stops and then starts all the cartridges present in your application. This behavior would also includes any database cartridge. This also meant our application was unavailable for that time; if you hit the URL for your app before the cartridges restart, you will receive a *503 Service Unavailable message*. In addition, for many of OpenShift's programming languages, you do not need to stop the server to deploy new code on the server. Going through a start/stop cycle for the application server significantly slows down the deployment experience.

We can signal to OpenShift that we want to just build and deploy without a restart by adding a marker file to our git repository. On OpenShift this behavior is called hot deploy. The hot deployment option is available on most of the core OpenShift application cartridges; the JBoss, Tomcat, PHP, Zend, Perl, Ruby, and Python cartridges all support this. 

//TODO may want to add a link to a marker file page if we make one

Enabling hot deployment is as simple as creating an empty file named _hot_deploy_ in the __.openshift/markers__ directory, adding it to the local repository with +git add+, doing a +git commit+, and then finally executing a +git push+:


++++
<screen>
[me@localhost ~/insultapp]$ <emphasis role="strong">touch .openshift/markers/hot_deploy</emphasis>
[me@localhost ~/insultapp]$ <emphasis role="strong">git add .openshift/markers/hot_deploy</emphasis>
[me@localhost ~/insultapp]$ <emphasis role="strong">git commit -m "Changing application to hot deploy"</emphasis>
</screen>
++++

And with that you have now enabled build and deploys without needing to stop and start the cartridges in your application. 

[WARNING]
====

There are times when you want the server to be stopped and then started again, such as when making changes to _server.xml_ in a Java application: you need the application server to restart in order to pick up the changes. There might also be times when you believe a bug in the code you are deploying or running has crashed the application server. Please remember to remove or rename the _hot_deploy_ file, +git add+, +git commit+, and _then_ +git push+ in this situation. 

This is also critical for any Apache HTTP server based projects, such as Python, Ruby, or PHP. If you add a database or your own environmental variables, Apache does not pick them up unless it is restarted. Therefore, if you add a database and don't restart Apache, it will not pick up the environment variables that give your application the connection strings. 

====


