---
layout: base
category: 02_Getting Started
breadcrumb: Getting Started
parent_url: getting-started-overview.html
nav_title: Overview
nav_priority: 1
meta_desc: Get started with Tomcat 7 on OpenShift.
---
= Getting Started

[[top]]
[float]
= Quickly Getting Started with Tomcat 6/7 (EWS 1.0/2.0)
[.lead]
It's easy to get up and running with Tomcat on OpenShift and the experience will be very similar to the experience you have had running it on any Linux system. We support both source and WAR file deploys and you can modify your Server.xml. One important caveat, your applications will not have write permissions to the *Webapp* directory, so you will have to write content to another directory.
On OpenShift we use http://www.jboss.org/products/webserver/overview/[JBoss EWS] 1.0 and  2.0 for Tomcat 6 and 7 respectively. EWS is a hardened and Red Hat supported version of Apache Tomcat. By versions use Java OpenJDK 1.7 

WARNING: EWS has had the clustering modules removed so you can not do Tomcat clustering with EWS. 
  
[.lead]

link:#step1[Step 1: Create Your First Tomcat Application] 
link:#step2[Step 2: Make Your First Change] 
// TODO link:#step3[Step 3: Deploying a WAR File]
// TODO add DB here, hot deploy, and server.xml link:#other[Other Hints and Tips]
// TODO link:#next[Next Steps] 

[[step1]]
== Step 1: Create Your First Tomcat Application

For this tutorial, we are going to assume you are creating an application titled *mytomcatapp* and your domain is *mydomain*. Before going through the rest of the tutorial it is assumed you have created an OpenShift account and installed the link:getting-started-client-tools.html[RHC command line tools]. Once that is completed you should open a terminal on your local machine and change into a directory where you want your source code to be located.  Then at the command prompt enter the follwing command to create a Tomcat application.

[source, console] 
--
$ rhc app-create mytomcatapp tomcat7 
--

or 

[source, console] 
--
$ rhc app-create mytomcatapp tomcat6 
--

and you should see output that looks something like this:

[source, console]
--
Using jbossews-2.0 (Tomcat 7 (JBoss EWS 2.0)) for 'tomcat7'

Application Options
-------------------
Domain:     mydomain
Cartridges: jbossews-2.0
Gear Size:  default
Scaling:    no

Creating application 'mytomcatapp' ... done


Waiting for your DNS name to be available ... done

Cloning into 'mytomcatapp'...
Warning: Permanently added 'mytomcatapp-mydomain.rhcloud.com,54.237.129.193' (RSA) to the list of known hosts.

Your application 'mytomcatapp' is now available.

  URL:        http://mytomcatapp-mydomain.rhcloud.com/
  SSH to:     541a13a04382ec1b7b0002f3@mytomcatapp-mydomain.rhcloud.com
  Git remote: ssh://541a13a04382ec1b7b0002f3@mytomcatapp-mydomain.rhcloud.com/~/git/mytomcatapp.git/
  Cloned to:  /home/me/git_demo/mytomcatapp

Run 'rhc show-app mytomcatapp' for more details about your app.

--

You can now see your application running at the *URL* listed in the output. You also now a have a local git repository for your application in the directory listed under *Cloned to:*

[[step2]]
== Step 2: Make Your First Change
As a developer on OpenShift, you make code changes on your local machine, check those changes in locally, and then "push" those changes to OpenShift. One of the primary advantages of Git is that it does not require a continuous online presence in order to run. You can easily check in (in Git terminology, 'commit') and revert changes locally before deciding to upload those changes to OpenShift.

=== Using the Git Repository

To make our first change, we need to edit the +index.html+ in the *mytomcatapp/src/main/webapp* directory. You can do this by going to the file in your terminal and editing with a comand line editor like VIM or EMacs, or you can edit with the editor of your choice. Strip out everything between the two *body* tags and change the content to look like this

[source, html]
--
<body>
	<h1>>Hello world!</h1>
</body>
--

Now that you have made your incredibly complicated code change, let's deploy the change to the server. To accomplish this task we need to use git.

We execute the following commands in the local git repository which is the directory that has the same name as the application, *mytomcatapp*. If you have not set your name and email in git, it will prompt you to take care of that first.

. If we had added any new files to the repository we would have done the following command to tell git to track new files as part of the repository.

[source, console]
--
$ git add --all .
--

. Next we commit all our local changes to the git repository and include a message for the commit

[source, console]
--
$ git commit -am "you message"
--

. Finally, we push these changes to the git repository in your OpenShift applications. 

[source, console]
--
$ git push
--

The output of the push command will first show you the git push and then it will show you the build process and deployment for your OpenShift application. When the build is finished, you can go back to your applications URL and see a page which just says "Hello World" in nice big font.

This is the basic process you will continue to follow as you develop your application: git add (optional), code change, git commit, and finally git push. 

If you are curious about git, here is a great resource link:http://git-scm.com/book[> to learn more about using Git]

[[step3]]
== Step 3: Deploying WAR files

OpenShift also supports if you would prefer to build a WAR file on your local machine and then deploy it. There are several process which are each very simple. Let's go through them in increasing order of complexity:

=== Using Git

. Take the WAR file and place it in the webapps directory
. Git add, git commit, and git push using the same commands as above
. Your application should automatically be deployed

WARNING: If you use this tecnhique, each time you push up a new WAR file it is adding a binary to your git repository. Git handles binaries, like WAR file, by basically storing the old one and adding the new version. This can quickly eat up your disk space on the gear with the git repository. 

// TODO left off here
=== Using SFTP 






=== When you Push...

Building without Jenkins uses your application space as part of the build and test process. Because of this, the application is shut down so its memory can be used for building. The following steps take place:

* You run a 'git push' on your computer - your changes are sent to your OpenShift application
* The application is shut down
* Your changes are copied on the server into the correct location
* OpenShift invokes your build hooks - script files you've placed in your Git repository
* Your application is started

[.lead]
link:getting-started-modifying-applications.html[> Learn More About Modifying Applications]

link:#top[Back to Top]

[[tutorials]]
== What's Next?

Access one of our more specific tutorials or learn more about specific cartridges on OpenShift.

include::_fragments/getting-started-tutorial-list.adoc[]

link:#top[Back to Top]
