---
layout: base
category: 02_Getting Started
breadcrumb: Getting Started
parent_url: getting-started-overview.html
nav_title: Overview
nav_priority: 1
meta_desc: Get started with Tomcat 7 on OpenShift.
---
= Getting Started

[[top]]
[float]
= Quickly Getting Started with Tomcat 6/7 (EWS 1.0/2.0)
[.lead]
It's easy to get up and running with Tomcat on OpenShift and the experience will be very similar to the experience you have had running it on any Linux system. We support both source and WAR file deploys and you can modify your Server.xml. One important caveat, your applications will not have write permissions to the *Webapp* directory, so you will have to write content to another directory.
On OpenShift we use http://www.jboss.org/products/webserver/overview/[JBoss EWS] 1.0 and  2.0 for Tomcat 6 and 7 respectively. EWS is a hardened and Red Hat supported version of Apache Tomcat. By versions use Java OpenJDK 1.7 

WARNING: EWS has had the clustering modules removed so you can not do Tomcat clustering with EWS. 
  
[.lead]

link:#step1[Step 1: Create Your First Tomcat Application] 
link:#step2[Step 2: Make Your First Change] 
link:#step3[Step 3: Deploying a WAR File]
link:#other[Other Hints and Tips] 
link:#next[Next Steps] 

[[step1]]
== Step 1: Create Your First Tomcat Application

For this tutorial, we are going to assume you are creating an application titled *mytomcatapp* and your domain is *mydomain*. Before going through the rest of the tutorial it is assumed you have created an OpenShift account and installed the link:getting-started-client-tools.html[RHC command line tools]. Once that is completed you should open a terminal on your local machine and change into a directory where you want your source code to be located.  Then at the command prompt enter the follwing command to create a Tomcat application.

[source, console] 
--
$ rhc app-create mytomcatapp tomcat7 
--

or 

[source, console] 
--
$ rhc app-create mytomcatapp tomcat6 
--

and you should see output that looks something like this:

[source, console]
--
Using jbossews-2.0 (Tomcat 7 (JBoss EWS 2.0)) for 'tomcat7'

Application Options
-------------------
Domain:     mydomain
Cartridges: jbossews-2.0
Gear Size:  default
Scaling:    no

Creating application 'mytomcatapp' ... done


Waiting for your DNS name to be available ... done

Cloning into 'mytomcatapp'...
Warning: Permanently added 'mytomcatapp-mydomain.rhcloud.com,54.237.129.193' (RSA) to the list of known hosts.

Your application 'mytomcatapp' is now available.

  URL:        http://mytomcatapp-mydomain.rhcloud.com/
  SSH to:     541a13a04382ec1b7b0002f3@mytomcatapp-mydomain.rhcloud.com
  Git remote: ssh://541a13a04382ec1b7b0002f3@mytomcatapp-mydomain.rhcloud.com/~/git/mytomcatapp.git/
  Cloned to:  /home/me/git_demo/mytomcatapp

Run 'rhc show-app mytomcatapp' for more details about your app.

--

You can now see your application running at the *URL* listed in the output. You also now a have a local git repository for your application in the directory listed under *Cloned to:*

[[step2]]
== Step 2: Make Your First Change
As a developer on OpenShift, you make code changes on your local machine, check those changes in locally, and then "push" those changes to OpenShift. One of the primary advantages of Git is that it does not require a continuous online presence in order to run. You can easily check in (in Git terminology, 'commit') and revert changes locally before deciding to upload those changes to OpenShift.

=== Using the Git Repository

To make our first change, we need to edit the +index.html+ in the *mytomcatapp/src/main/webapp* directory. You can do this by going to the file in your terminal and editing with a comand line editor like VIM or EMacs, or you can edit with the editor of your choice. Strip out everything between the two *body* tags and change the content to look like this

[source, html]
--
<body>
	<h1>>Hello world!</h1>
</body>
--

Now that you have made your incredibly complicated code change, let's deploy the change to the server. To accomplish this task we need to use git.

We execute the following commands in the local git repository which is the directory that has the same name as the application, *mytomcatapp*. If you have not set your name and email in git, it will prompt you to take care of that first.

. If we had added any new files to the repository we would have done the following command to tell git to track new files as part of the repository.

[source, console]
--
$ git add --all .
--

. Next we commit all our local changes to the git repository and include a message for the commit

[source, console]
--
$ git commit -am "you message"
--

. Finally, we push these changes to the git repository in your OpenShift applications. 

[source, console]
--
$ git push
--

The output of the push command will first show you the git push and then it will show you the build process and deployment for your OpenShift application. When the build is finished, you can go back to your applications URL and see a page which just says "Hello World" in nice big font.

This is the basic process you will continue to follow as you develop your application: git add (optional), code change, git commit, and finally git push. 

If you are curious about git, here is a great resource link:http://git-scm.com/book[> to learn more about using Git]

[[step3]]
== Step 3: Deploying WAR files

OpenShift also supports if you would prefer to build a WAR file on your local machine and then deploy it. There are several process which are each very simple. There is a https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges[great knowledgebase article] that covers deploying WAR files with both Git and SFTP/SCP.


[[other]]
== Other hints and tips


=== Server.xml
Most of the behavior of Tomcat can be controlled through http://tomcat.apache.org/tomcat-7.0-doc/config/[the server.xml file]. In OpenShift you can find the server.xml inside your applications git repository. Navigate to the *{git repo}/.openshift/config/* directory and you will see the server.xml there. Please be careful when making a change to the file as you have the potential to make your application not work correctly. You also need to make sure the Tomcat server restarts after you make the change. 

=== Hot Deploy and Other Markers 

When you do your normal git push above, if you pay attention, you will see that Openshift starts and stops the Tomcat server on each build. For Java applications you can actually just build the WAR file and deploy your code without restarting the server. We have written link:hot-deploy.html[a document] explaining how OpenShift uses a marker in the git repository to turn on this build style.  
// TODO need a doc that describes markers that we point to here

==== Other Markers

Adding marker files to .openshift/markers will have the following effects:

[cols="2*", options="header"]
|===
|Marker
|Effect

|enable_jpda
|Will enable the JPDA socket based transport on the java virtual machine running the Tomcat server. This enables you to remotely debug code running inside Tomcat.

|skip_maven_build
|Maven build step will be skipped

|force_clean_build
|Will start the build process by removing all non-essential Maven dependencies. Any current dependencies specified in your pom.xml file will then be re-downloaded.

|java7
|Will run Tomcat with Java7 if present. If no marker is present then the baseline Java version will be used (currently Java6)

=== Adding a Database to Your Appliction

We have link:adding-database.html[a document] to cover how to add a database to your application. As noted in the document, you should only use environment variables to specify the connection parameters to connect to your database. Using hard coded names, ports, or credentials limits the resusability of your app and can potentially break your app during OpenShift maintenance.

By default, the three provided datastores: MySQL, Postgresql, and MongoDB have JNDI entries in your **server.xml**. As noted above you can edit your **server.xml**, which allows you to delete or add other JNDI sources to your application. The syntax is standard syntax, there are no modification you need to make for OpenShift. Once again, please use environment variables rather than hard coding in values.


=== Configuring JVM properties

You can also use environment variables to configure JVM properties. By setting the *JAVA_OPTS_EXT* environment variable, you can add extra JAVA_OPTS before the JVM is invoked. Here is an example setting the setting other garbage collection properties. 

[source, console]
--

$ rhc env-set JAVA_OPTS_EXT="-XX:+PrintGCDetails  -Xloggc:$OPENSHIFT_LOG_DIR/gc.log" --app mytomcatapp

--

WARNING: Please note you can not overwrite or change any of the startup parameters already set for Tomcat. If you want to see what is already provided you can SSH into your application and run the following command:

[source, console]
--

$ ps axwwww | grep java

--


[[next]]
== Next Steps

Of course the best next step is to start creating an application. If you want to follow a link:tomcat-creating-application.html [more involved tutorial] we have one that will talk you more in depth in creating and maintaining application. 

You can also look at the https://www.openshift.com/application-gallery[application gallery] and https://www.openshift.com/developer-spotlight[developer spotlight] to see what other developers have created on OpenShift. 

Finally, you can look through our http://origin.ly/[quickstarts and community cartridges] to see other exciting technology you can use in your applications. 

link:#top[Back to Top]


Access one of our more specific tutorials or learn more about specific cartridges on OpenShift.

include::_fragments/getting-started-tutorial-list.adoc[]

link:#top[Back to Top]
