Main Header
===========
:Author:    Shawn Purtell
:Email:     spurtell@redhat.com
:Date:      2014-07-21
:Revision:  1.0
:source-highlighter: coderay
:awestruct-layout: base

== Developer Center
This is the dev center content (in English).

include::/en/fragments/sample.adoc[]

=== Paragraphs

[.lead]
This text will be styled as a lead paragraph (i.e., larger font).

Normal paragraphs don't require any special markup. +

 A literal paragraph is a series of indented
 lines, used in some structures.

=== Admonitions

NOTE: This is a NOTE.

TIP: This is a TIP.

IMPORTANT: This is IMPORTANT.

WARNING: This is a WARNING.

CAUTION: This is a CAUTION.

[TIP]
====
An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.
====

=== Font Styling
_italic phrase_ +
*bold phrase* +
*_bold italic phrase_* +
^super^script phrase +
~sub~script phrase +
Do werewolves believe in [small]#small print#? +

=== Lists

==== Unordered List
* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson

==== Checklist
- [*] checked
- [x] also checked
- [ ] not checked
-     normal list item

==== Ordered List
. Step 1
. Step 2
. Step 3

=== Q & A
[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.
What is the answer to the Ultimate Question?:: 42

=== Links
http://asciidoctor.org - automatic!

http://asciidoctor.org[Asciidoctor]

https://github.com/asciidoctor[Asciidoctor @ *GitHub*]

=== YouTube

video::rbFIHgHDRgo[youtube, width=640, height=480]

=== Content/Code Blocks

==== Inline

Reference code like +types+ or +methods+ inline.

==== Block

....
error: The requested operation returned error: 1954 Forbidden search for defensive operations manual
absolutely fatal: operation initiation lost in the dodecahedron of doom
would you like to die again? y/n
....


==== Standard Code Block

.Gemfile.lock
----
GEM
  remote: https://rubygems.org/
  specs:
    asciidoctor (0.1.4)

PLATFORMS
  ruby

DEPENDENCIES
  asciidoctor (~> 0.1.4)
----

==== Block w/Coloring

[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----

==== Block w/Notes

[source,ruby]
----
require 'sinatra' <1>

get '/hi' do      <2>
  "Hello World!"  <3>
end
----
<1> Library import
<2> URL mapping
<3> Content for response


'''

Content last updated {date}
