---
title: SQLite
description: SQLite Developers - OpenShift Resources to get your SQLite applications hosted in the cloud.
---

[[top]]
[float]
= Using SQLite with OpenShift Online
[.lead]
SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine. SQLite is the most widely deployed SQL database engine in the world. The source code for SQLite is in the public domain.


== Installation
SQLite is installed as part of the base set of packages for OpenShift Online and is available to every application without having to install any cartridges.  

=== Environment Variables
There are no environment variables for SQLite.  The `sqlite3` executable should be included in your PATH already and available for use within your application.
If you need the exact path to the executable, you can ssh into your application and run the following command: +
[source,console]
--
which sqlite3
--
Which should output the location as `/usr/bin/sqlite3`.

=== Using SQLite
To get started using SQLite you should consult the `SQLite Programming Interfaces` section of the link:http://www.sqlite.org/docs.html[Official SQLite Documentation] page.

link:#top[Back to Top]
