[[rhc-setup]]
== Setting up Your Machine
After installation is complete, open a Terminal window and run:
[source]
----
$ rhc setup
----
The OpenShift interactive setup wizard displays and prompts you to complete the rest of the process.

You'll be prompted for your OpenShift username and password:

[source]
----
Login to openshift.redhat.com: user@example.com
Password: password
----

You are then prompted to generate an authorization token. Answering yes stores a token in your home directory to be used on subsequent requests. When it expires, you are prompted for your password again.

[source]
----
OpenShift can create and store a token on disk which allows to you to access the server without using your password. The key is stored in your home directory and should be kept secret. You can delete the key at any time by running 'rhc logout'.
Generate a token now? (yes|no) yes
Generating an authorization token for this client ... lasts about 1 day
----

After creating a configuration file, setup will configure SSH keys so that your system can remotely connect to your applications, including deploying your applications using Git:

[source]
----
No SSH keys were found. We will generate a pair of keys for you.
Created: C:\Users\User1\.ssh\id_rsa.pub
----

NOTE: The path shown here is for Windows and will differ depending on your operating system.

After the new SSH keys are generated, the public key, *id_rsa.pub*, must be uploaded to the OpenShift server to authenticate your system to the remote server. Enter a name to use for your key, or leave it blank to use the default name. In the following example the default name is used.

[source]
----
Your public ssh key must be uploaded to the OpenShift server to access code.
Upload now? (yes|no) yes

Since you do not have any keys associated with your OpenShift account, your new key will be uploaded as the 'default' key

Uploading key 'default' from C:\Users\User1\.ssh\id_rsa.pub ... done
----

NOTE: The path shown here is for Windows and will differ depending on your operating system.

After verifying that link:#installing-git[Git is installed], you will be asked to set up your domain if you don't already have one:

[source]
----
Checking for a domain ... none

Your domain is unique to your account and is the suffix of the public URLs we assign to your applications. You may configure your domain here or leave it blank and use 'rhc domain create' to create a domain later. You will not be able to create applications without first creating a domain.

Please enter a domain (letters and numbers only) |<none>|: MyDomain
Your domain name 'MyDomain' has been successfully created
----

Finally, the setup wizard verifies whether any applications exist under your domain. In the example below, no applications have been created. In this case the setup wizard shows the types of applications that can be created with the associated commands. The setup wizard then completes by displaying the current gear consumption along with the gear sizes available to the given user.

[source]
----
Checking for applications ... none

Run 'rhc app create' to create your first application.

Do-It-Yourself                            rhc app create <app name> diy-0.1
JBoss Application Server 7.1              rhc app create <app name> jbossas-7
JBoss Enterprise Application Platform 6.0 rhc app create <app name> jbosseap-6.0
Jenkins Server 1.4                        rhc app create <app name> jenkins-1.4
Node.js 0.10                              rhc app create <app name> nodejs-0.10
PHP 5.3                                   rhc app create <app name> php-5.3
PHP 5.4                                   rhc app create <app name> php-5.4
Perl 5.10                                 rhc app create <app name> perl-5.10
Python 2.6                                rhc app create <app name> python-2.6
Python 2.7 Community Cartridge            rhc app create <app name> python-2.7
Python 3.3 Community Cartridge            rhc app create <app name> python-3.3
Ruby 1.8                                  rhc app create <app name> ruby-1.8
Ruby 1.9                                  rhc app create <app name> ruby-1.9
Tomcat 6 (JBoss EWS 1.0)                  rhc app create <app name> jbossews-1.0
Tomcat 7 (JBoss EWS 2.0)                  rhc app create <app name> jbossews-2.0
Zend Server 5.6                           rhc app create <app name> zend-5.6

You are using 0 of 3 total gears
The following gear sizes are available to you: small

Your client tools are now configured.
----

You are now ready to create and manage an application using OpenShift.

If you cannot run OpenShift client tools at this point, please visit the link:/help.html[Help Center] for more assistance.

link:#top[Back to Top]

[[creating-app]]
== Creating an Application
Now that you have rhc installed and configured, you are ready to create an application.

You can create a new application with either the management console or the client tools.

=== Using the Web Console
You can see the full list of application types and create a new application through the OpenShift web console:
link:https://openshift.redhat.com/app/login?then=%2Fapp%2Fconsole%2Fapplication_types[Create an Application (requires login)]

=== Using the Client tools (rhc)
Alternatively, you can use rhc to create an application using the following command:

[source]
----
$ rhc app create <app_name> <web_cartridge_name>
----

For example, to create a PHP 5.4 application named *myfirstphpapp*, use the following command:

[source]
----
$ rhc app create myfirstphpapp php-5.4
----

There are a number of options available when creating a new application. To learn more about creating an application on OpenShift, see link:/managing-your-applications/creating-applications.html[Creating Applications].

link:#top[Back to Top]

[[making-first-change]]
== Making Your First Change
OpenShift uses Git to manage application deployments on OpenShift. You make code changes on your local machine, check those changes in locally, and then push those changes to OpenShift.

=== Using the Git Repository
Every OpenShift application you create has its own Git repository that only you can access.

==== Command Line (RHC)
If you create your application from the command line, *rhc* will automatically download a copy of that repository (Git calls this 'cloning') to your local system.

==== Web Console
If you create an application from the web console, you'll need to tell Git to clone the repository. Find the Git URL from the application page, and then run:

[source]
----
$ git clone <git_url> <directory to create>
----

=== Submitting Changes
Once you make changes to your local repository, you need to *add* and *commit* those changes - `add` tells Git that a file or set of files will become part of a larger check in, and `commit` completes the check in. Git requires that each commit have a message to describe it.

[source]
----
$ git add .
$ git commit -m "A change to my application"
----

Finally, you're ready to send your changes to your application - you'll 'push' these changes with:

[source]
----
$ git push
----

The output of the push command will contain information from OpenShift about your deployment.
[.lead]
link:http://git-scm.com/book[-> Learn more about using Git] +
link:/managing-your-applications/modifying-applications.html[-> Learn More About Modifying Applications]

link:#top[Back to Top]

[[remote-access]]
== Remote Access
OpenShift allows you to remotely access your application's gears in order to perform various tasks such as troubleshooting, working with log files, and managing environment variables

Once you have created an application and set up your SSH keys (either by `rhc setup` or manual upload), you can SSH into the remote server using the `rhc ssh` command.

To SSH into a specific application:
[source]
----
$ rhc ssh <app_name>
----

You should then connect to your application's primary gear:
[source]
----
*********************************************************************

You are accessing a service that is for use only by authorized users.
If you do not have authorization, discontinue use at once.
Any use of the services is subject to the applicable terms of the
agreement which can be found at:
https://www.openshift.com/legal

*********************************************************************

Welcome to OpenShift shell

This shell will assist you in managing OpenShift applications.

!!! IMPORTANT !!! IMPORTANT !!! IMPORTANT !!!
Shell access is quite powerful and it is possible for you to
accidentally damage your application.  Proceed with care!
If worse comes to worst, destroy your application with "rhc app delete"
and recreate it
!!! IMPORTANT !!! IMPORTANT !!! IMPORTANT !!!

Type "help" for more info.
----

Now that you're connected, you can use the OpenShift shell to explore and modify your application.

=== Common Commands
Once you have SSHed into your application, you can use many link:/managing-your-applications/linux-commands.html[common Linux Commands].

In addition to Linux commands, the following commands are available to help control your OpenShift application and environment:

[source]
----
gear            control your application (start, stop, restart, etc)
or deps with --cart      (gear start --cart mysql-5.1)
tail_all        tail all log files
export          list available environment variables <1>
rm              remove files / directories
ls              list files / directories
ps              list running applications
kill            kill running applications
mysql           interactive MySQL shell
mongo           interactive MongoDB shell
psql            interactive PostgreSQL shell
quota           list disk usage
----
<1> Find more information on using link:/managing-your-applications/environment-variables.html[Environment Variables]

link:#top[Back to Top]

[[next-steps]]
== Next Steps
This guide has just scratched the surface of what you can do with OpenShift Online. Feel free to explore other topics under link:/managing-your-applications/common-rhc-commands.html[Managing Your Applications] or visit one of the technology-specific tutorials below:
