---
title: Account FAQs
description: This page provides answers to common account-related questions about OpenShift.
---

[[top]]
[float]

[.lead]
Find answers to some common account-related questions about OpenShift.

NOTE: Troubleshooting a **technical issue**? Browse the link:/faq/troubleshooting.html[Technical FAQs].

== In This Guide
link:#_why_didn_t_i_receive_an_account_verification_or_password_reset_email[Why didn't I receive an account verification or password reset email?] +
link:#_how_can_i_upgrade_my_account[How can I upgrade my account?] +
link:#_can_i_pay_for_my_bronze_or_silver_plan_with_paypal[Can I pay for my Bronze or Silver Plan with Paypal?] +
link:#_what_is_my_current_account_usage[What is my current account usage?] +
link:#_why_can_t_i_downgrade_to_the_free_plan[Why can't I downgrade to the Free Plan?] +
link:#_can_i_change_my_login_id[Can I change my login ID?] +
link:#_can_i_change_my_email_address[Can I change my email address?] +
link:#_how_can_i_transfer_application_ownership_from_one_user_to_another[How can I transfer application ownership from one user to another?] +
link:#_how_can_i_get_more_resources[How can I get more resources?] +
link:#_how_do_i_indicate_that_i_am_exempt_from_taxes[How do I indicate that I am exempt from taxes?] +
link:#_how_do_i_delete_my_account[How do I delete my account?] +

=== Why didn't I receive an account verification or password reset email?
The most common reasons for this:

* The email used to make the request was not correct or not a valid email address.
* The email may have been filed into your spam or junk folder.
* The OpenShift username is case-sensitive (even though email addresses are not).

If you signed up with your Red Hat Network (RHN) account, you can try resetting the password link:https://www.redhat.com/wapps/sso/lostPassword.html[here].

link:#top[Back to Top]

=== How can I upgrade my account?
If you are an existing user, the easiest way to upgrade your account is to go link:https://openshift.redhat.com/app/account/plan[here].

You can also manage your plan by going to your link:https://openshift.redhat.com/app/console/settings[Account Settings] page and clicking the *Upgrade your account* link at the top of the page.

If you are a new user, you can sign up for the plan you want directly from the link:https://www.openshift.com/pricing[Pricing Page].

link:#top[Back to Top]

=== Can I pay for my Bronze or Silver Plan with Paypal?
Currently OpenShift Online only accepts credit card payments from the US, Canada, and Europe. Please see the link:https://www.openshift.com/pricing[Pricing Page] for more details.

link:#top[Back to Top]

=== What is my current account usage?
You can see current usage on the link:https://openshift.redhat.com/app/account[My Account] page (login required).

link:#top[Back to Top]

=== Why can't I downgrade to the Free Plan?
In order to downgrade from the Silver Plan or Bronze Plan to the Free Plan, you will need to reduce your account's resource usage to be within the Free plan's resource limits.
Make sure your apps are consuming only up to link:/managing-your-applications/resource-management.html[3 small gears with no additional storage], and remove any link:/managing-your-applications/collaboration.html#team-management[teams] that are set up.

NOTE: Note that it is not possible to modify gear sizes of already deployed applications; if any app is deployed on _medium_ or _large_ gear(s), it needs to be deleted (you may want to download its link:/managing-your-applications/backing-up-applications.html[backup snapshot] first).

link:#top[Back to Top]

=== Can I change my login ID?
Your email address/RHN username serves as the username for your OpenShift account. Currently, our system does not allow username changes.

link:#top[Back to Top]

=== Can I change my email address?
Yes, you can link:https://sso.redhat.com/[log in] and update the email address associated with this account. If you have not signed up using a Red Hat account when creating the OpenShift Online account, you will be asked to complete the Red Hat Account registration process.

link:#top[Back to Top]

=== How can I transfer application ownership from one user to another?
An application can be transferred from one account to another by following these steps:

*Step 1: Backup your application into a local .TAR file:*
[source]
--
$ rhc snapshot-save <app_name>
--

*Step 2: Transfer the .TAR file from Step 1 to the new owner.*

*Step 3: The new owner must create a new application with the same name and cartridges as the original application.*

The original account owner can get this information by running:
[source]
--
$ rhc app-show <app_name>
--

*Step 4: Restore the backed up application to the new account.*

The new owner runs:
[source]
--
$ rhc snapshot-restore <app_name> --filepath <path_to_tar_file>
--

You can then delete the original application as needed.

link:#top[Back to Top]

=== How can I get more resources?
If you are using the OpenShift Online Free Plan and need larger gears, more gears, or additional storage, you can link:#_how_can_i_upgrade_my_account[upgrade your account] to purchase more resources.

link:#top[Back to Top]

=== How do I indicate that I am exempt from taxes?
To qualify for tax exempt status you must submit a certificate to Red Hat. Upon receipt of your certificate we will refund all previously paid taxes to your credit card.

To begin the process, please email customerservice@redhat.com.

link:#top[Back to Top]

=== How do I delete my account?
In order to delete your account, please do the following:

. Delete all of your applications and ssh keys.
. Delete your domain.
. Downgrade to the Free Plan if you are the Bronze or Silver Plan.
. Unsubscribe from all notifications by using the unsubscribe link in any OpenShift email
. Please link:https://www.surveymonkey.com/s/come-back-soon[fill out this form] and optional survey and your account will be marked for deletion.

Please note that at this time, these deletes are soft-deletes due to user-based requirements. Soft-deletes enable you to simply login to re-enable your account and continue using OpenShift Online.

At this time, OpenShift Online accounts cannot be permanently deleted.

link:#top[Back to Top]
