---




title: Markers

description: Control your app using markers.
---


[[top]]
[float]
= Markers
[.lead]
Marker files can be used to customize various aspects of the cartridge's build and deployment process.


[[using-markers]]
== Using markers
Enabling a marker is as simple as creating an empty file of a given name in the `.openshift/markers/` directory and link:/managing-your-applications/modifying-applications.html[pushing] it to your repository, in order to trigger the required functionality.

TIP: For example, creating the `.openshift/markers/hot_deploy` in an PHP app will prevent the Apache process from being restarted during the link:/managing-your-applications/deployments.html[deployment].

Creating an empty file in the current directory is typically done using `touch marker_file` on Linux and Mac OS systems or by `copy NUL > marker_file` when on Windows.

[[common-markers]]
== Common markers
Although markers are generally cartridge-specific, you can expect these to work with most of the cartridges:

[cols="1,3",options="header"]
|===
|Marker |Effect

|disable_auto_scaling
|Will prevent scalable applications from scaling up or down according to application load.

|force_clean_build
|Will remove all previous dependencies and start installing required dependencies from scratch

|hot_deploy
|Will prevent shutdown and startup of the application during builds.
|===

[[cartridge-specific-markers]]
== Cartridge-specific markers
Below you can find links to markers available in various cartridges:

link:/servers/jbossas/markers.html[JBoss AS markers] +
link:/servers/jbosseap/markers.html[JBoss EAP markers] +
link:/languages/nodejs/markers.html[Node.js markers] +
link:/languages/perl.html#_markers[Perl markers] +
link:/languages/php/markers.html[PHP markers] +
link:/languages/python/markers.html[Python markers] +
link:/languages/ruby/markers.html[Ruby markers] +
link:/servers/tomcat/markers.html[Tomcat (JBoss EWS) markers] +
link:/servers/wildfly/markers.html[WildFly markers] +

link:#top[Back to Top]
